/*
 * Copyright 2016-2023, 2026 Uber Technologies, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/** @file faceijk.c
 * @brief   Functions for working with icosahedral face-centered hex IJK
 *  coordinate systems.
 */

/* The project's H3_HAS_AVX2 / H3_HAS_AVX512 macros are defined as CMake
 * target compile definitions on the whole `h3` library, so they're set
 * for every translation unit — including this one, which is built with
 * the project default flags (no per-file `-mavx2` / `-mavx512f`). The
 * per-file ISA flags only land on files under `src/h3lib/lib/simd/`,
 * applied by `cmake/H3Simd.cmake`.
 *
 * If we entered the `#if defined(H3_HAS_AVX2)` / `#if defined(H3_HAS_AVX512)`
 * blocks below in a TU that wasn't compiled with the corresponding ISA
 * flag, GCC fires `-Wpsabi` on functions whose signatures contain AVX
 * vector returns, AND fails to inline `_mm512_*` `always_inline`
 * intrinsics with "target specific option mismatch". CI runs with
 * `-Werror` so both become hard build failures.
 *
 * Force-cancel the project macros for THIS TU when the compiler-set
 * predefines say the ISA isn't actually enabled here. Inside SIMD
 * source files (where the per-file flag is in effect), `__AVX2__` /
 * `__AVX512F__` are defined and the project macros stay enabled. */
#if defined(H3_HAS_AVX2) && !defined(__AVX2__)
#undef H3_HAS_AVX2
#endif
#if defined(H3_HAS_AVX512) && !defined(__AVX512F__)
#undef H3_HAS_AVX512
#endif

#include "faceijk.h"

#include <assert.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "alloc.h"
#include "approx_libm.h"
#include "baseCells.h"
#include "constants.h"
#include "coordijk.h"
#include "h3Index.h"
#include "h3omp.h"
#include "latLng.h"
#include "vec3d.h"

/** square root of 7 and inverse square root of 7 */
#define M_SQRT7 2.6457513110645905905016157536392604257102
#define M_RSQRT7 0.37796447300922722721451653623418006081576

/* Powers of M_RSQRT7 for resolution scaling in _hex2dToVec3. The original
 * code spun a `for (i=0; i<res; i++) r *= M_RSQRT7` loop on every call;
 * this lookup replaces that 0..15-iteration multiply chain with a single
 * load. Index 16 covers the substrate-classIII path which needs
 * M_RSQRT7^(res+1) at res=15. Constant-folded at compile time via the
 * pow-of-two macro decomposition. */
#define _R1 M_RSQRT7
#define _R2 (_R1 * _R1)
#define _R4 (_R2 * _R2)
#define _R8 (_R4 * _R4)
#define _R16 (_R8 * _R8)
static const double RSQRT7_POW[17] = {
    1.0,                  /* ^0  */
    _R1,                  /* ^1  */
    _R2,                  /* ^2  */
    _R2 *_R1,             /* ^3  */
    _R4,                  /* ^4  */
    _R4 *_R1,             /* ^5  */
    _R4 *_R2,             /* ^6  */
    _R4 * _R2 * _R1,      /* ^7  */
    _R8,                  /* ^8  */
    _R8 *_R1,             /* ^9  */
    _R8 *_R2,             /* ^10 */
    _R8 * _R2 * _R1,      /* ^11 */
    _R8 *_R4,             /* ^12 */
    _R8 * _R4 * _R1,      /* ^13 */
    _R8 * _R4 * _R2,      /* ^14 */
    _R8 * _R4 * _R2 *_R1, /* ^15 */
    _R16,                 /* ^16 */
};
#undef _R1
#undef _R2
#undef _R4
#undef _R8
#undef _R16

/* Per-face tangent basis precomputed from faceCenterPoint below.
 * Replaces the per-call _vec3TangentBasis(faceCenterPoint[face], …) work
 * inside _hex2dToVec3 with a constant lookup. Generated by
 * scripts/dev/gen-face-tangent-basis.py — re-run to verify reproducibility.
 * Each value is the bit-equivalent runtime _vec3TangentBasis result for the
 * corresponding face center (printed at full %.18e precision so the text
 * round-trip preserves the exact IEEE-754 double). */
static const Vec3d faceNorthDir[NUM_ICOSA_FACES] = {
    {-2.280784957754315445e-01, -6.827596045277436465e-01,
     +6.941322080050280618e-01}, // face  0
    {+7.944029645987294996e-01, -5.489178021239006222e-01,
     +2.600253378965518558e-01}, // face  1
    {-1.925934259845962782e-01, +8.481867087336083522e-01,
     +4.934440995646466321e-01}, // face  2
    {-5.084246035199391223e-01, +2.459758791526299448e-01,
     +8.252274167832061025e-01}, // face  3
    {-4.345021989011208507e-01, -1.847237416405625166e-01,
     +8.815242358689869828e-01}, // face  4
    {+1.841679435875451590e-02, -1.708979839989220317e-01,
     +9.851165924654052830e-01}, // face  5
    {+5.595263084115215113e-01, -1.062563038079442218e-01,
     +8.219731796697802295e-01}, // face  6
    {+1.296256224228556908e-01, +3.936880123167181833e-01,
     +9.100587601740882659e-01}, // face  7
    {+5.867569493861568564e-02, -5.287341391493560749e-02,
     +9.968759024695352799e-01}, // face  8
    {+2.001736005560225962e-01, +1.110496712436479239e-01,
     +9.734467115138433213e-01}, // face  9
    {+5.867569493861567176e-02, -5.287341391493560749e-02,
     +9.968759024695352799e-01}, // face 10
    {+2.001736005560225684e-01, +1.110496712436479516e-01,
     +9.734467115138433213e-01}, // face 11
    {+1.841679435875447773e-02, -1.708979839989220317e-01,
     +9.851165924654052830e-01}, // face 12
    {+5.595263084115215113e-01, -1.062563038079442773e-01,
     +8.219731796697802295e-01}, // face 13
    {+1.296256224228557463e-01, +3.936880123167181278e-01,
     +9.100587601740882659e-01}, // face 14
    {-5.084246035199391223e-01, +2.459758791526298893e-01,
     +8.252274167832061025e-01}, // face 15
    {-4.345021989011209618e-01, -1.847237416405624333e-01,
     +8.815242358689869828e-01}, // face 16
    {-2.280784957754316278e-01, -6.827596045277436465e-01,
     +6.941322080050280618e-01}, // face 17
    {+7.944029645987291666e-01, -5.489178021239010663e-01,
     +2.600253378965518558e-01}, // face 18
    {-1.925934259845961116e-01, +8.481867087336084632e-01,
     +4.934440995646466877e-01}, // face 19
};
static const Vec3d faceEastDir[NUM_ICOSA_FACES] = {
    {-9.484780715185177069e-01, +3.168427809632304304e-01,
     +2.775557561562891351e-17}, // face  0
    {-5.684722271714832686e-01, -8.227024534633973207e-01,
     +0.000000000000000000e+00}, // face  1
    {+9.751766364454802494e-01, +2.214283805903834723e-01,
     +0.000000000000000000e+00}, // face  2
    {+4.355092432928927559e-01, +9.001842583640594642e-01,
     +2.775557561562891351e-17}, // face  3
    {-3.912488275764173795e-01, +9.202849313772766271e-01,
     +0.000000000000000000e+00}, // face  4
    {-9.942434602486270867e-01, -1.071444900722233196e-01,
     +3.469446951953614189e-18}, // face  5
    {-1.865696501818840669e-01, -9.824417365070610142e-01,
     -1.387778780781445676e-17}, // face  6
    {+9.498376754266557587e-01, -3.127433298091056857e-01,
     +0.000000000000000000e+00}, // face  7
    {+6.694212938675645486e-01, +7.428829862883359336e-01,
     -6.938893903907228378e-18}, // face  8
    {-4.851157986078958873e-01, +8.744499196300629107e-01,
     +0.000000000000000000e+00}, // face  9
    {-6.694212938675645486e-01, -7.428829862883358226e-01,
     -6.938893903907228378e-18}, // face 10
    {+4.851157986078959983e-01, -8.744499196300627997e-01,
     +0.000000000000000000e+00}, // face 11
    {+9.942434602486270867e-01, +1.071444900722231253e-01,
     +3.469446951953614189e-18}, // face 12
    {+1.865696501818841502e-01, +9.824417365070610142e-01,
     +1.387778780781445676e-17}, // face 13
    {-9.498376754266556476e-01, +3.127433298091057412e-01,
     +0.000000000000000000e+00}, // face 14
    {-4.355092432928926449e-01, -9.001842583640594642e-01,
     +2.775557561562891351e-17}, // face 15
    {+3.912488275764171575e-01, -9.202849313772767381e-01,
     +0.000000000000000000e+00}, // face 16
    {+9.484780715185177069e-01, -3.168427809632305414e-01,
     -2.775557561562891351e-17}, // face 17
    {+5.684722271714837127e-01, +8.227024534633970987e-01,
     +1.387778780781445676e-17}, // face 18
    {-9.751766364454803604e-01, -2.214283805903832780e-01,
     +1.387778780781445676e-17}, // face 19
};

/** @brief icosahedron face centers in x/y/z on the unit sphere */
static const Vec3d faceCenterPoint[NUM_ICOSA_FACES] = {
    {0.2199307791404606, 0.6583691780274996, 0.7198475378926182},    // face  0
    {-0.2139234834501421, 0.1478171829550703, 0.9656017935214205},   // face  1
    {0.1092625278784797, -0.4811951572873210, 0.8697775121287253},   // face  2
    {0.7428567301586791, -0.3593941678278028, 0.5648005936517033},   // face  3
    {0.8112534709140969, 0.3448953237639384, 0.4721387736413930},    // face  4
    {-0.1055498149613921, 0.9794457296411413, 0.1718874610009365},   // face  5
    {-0.8075407579970092, 0.1533552485898818, 0.5695261994882688},   // face  6
    {-0.2846148069787907, -0.8644080972654206, 0.4144792552473539},  // face  7
    {0.7405621473854482, -0.6673299564565524, -0.0789837646326737},  // face  8
    {0.8512303986474293, 0.4722343788582681, -0.2289137388687808},   // face  9
    {-0.7405621473854481, 0.6673299564565524, 0.0789837646326737},   // face 10
    {-0.8512303986474292, -0.4722343788582682, 0.2289137388687808},  // face 11
    {0.1055498149613919, -0.9794457296411413, -0.1718874610009365},  // face 12
    {0.8075407579970092, -0.1533552485898819, -0.5695261994882688},  // face 13
    {0.2846148069787908, 0.8644080972654204, -0.4144792552473539},   // face 14
    {-0.7428567301586791, 0.3593941678278027, -0.5648005936517033},  // face 15
    {-0.8112534709140971, -0.3448953237639382, -0.4721387736413930}, // face 16
    {-0.2199307791404607, -0.6583691780274996, -0.7198475378926182}, // face 17
    {0.2139234834501420, -0.1478171829550704, -0.9656017935214205},  // face 18
    {-0.1092625278784796, 0.4811951572873210, -0.8697775121287253},  // face 19
};

/* Generated by scripts/dev/gen-face-azimuth-trig.py — do not edit by hand.
 * Precomputed cos/sin per icosahedron face of the azimuth from face
 * center to vertex 0, used by both `_hex2dToVec3` (decoder) and
 * `_vec3ToHex2d` (encoder) to eliminate the atan2 + sincos round-trip
 * via the angle-subtraction identity:
 *   cos(A - B) = cos A cos B + sin A sin B
 *   sin(A - B) = sin A cos B - cos A sin B
 * with B's cos/sin recovered from the unit-tangent-plane components
 * directly (cos(atan2(y, x)) = x/r and sin = y/r, with r = 1 by
 * construction in the tangent-basis projection).
 *
 * Layout: [face][0] = no Class III rotation,
 *         [face][1] = with M_AP7_ROT_RADS subtracted (Class III). */
static const double faceAxesAzCosCII[NUM_ICOSA_FACES][2] = {
    {+7.880095697511676489e-01, +5.430760360391094776e-01}, // face  0
    {+8.664014335865634076e-01, +6.552223597075158557e-01}, // face  1
    {+7.107632630497379145e-01, +9.018600943920073165e-01}, // face  2
    {+9.087699854193629356e-01, +9.952995563794687639e-01}, // face  3
    {+9.883310851710102041e-01, +8.840263660420918379e-01}, // face  4
    {-9.010053124560770677e-01, -7.093729780833415433e-01}, // face  5
    {-9.874446780572173621e-01, -8.813412659202572996e-01}, // face  6
    {-9.244066537350563717e-01, -9.983273763925964994e-01}, // face  7
    {-9.384391994818986893e-01, -9.998149327154995936e-01}, // face  8
    {-9.904409656999425549e-01, -8.907281704829727031e-01}, // face  9
    {+9.384391994818988003e-01, +7.736684547013850111e-01}, // face 10
    {+9.904409656999425549e-01, +9.810293177546717258e-01}, // face 11
    {+9.010053124560769566e-01, +9.933670124215349118e-01}, // face 12
    {+9.874446780572173621e-01, +9.847537709180538279e-01}, // face 13
    {+9.244066537350562607e-01, +7.486369922333722116e-01}, // face 14
    {-9.087699854193629356e-01, -7.221142867486942674e-01}, // face 15
    {-9.883310851710103151e-01, -9.837438227844008676e-01}, // face 16
    {-7.880095697511678710e-01, -9.461220727470304181e-01}, // face 17
    {-8.664014335865634076e-01, -9.821224465924063285e-01}, // face 18
    {-7.107632630497378035e-01, -4.413562163725573417e-01}, // face 19
};

static const double faceAxesAzSinCII[NUM_ICOSA_FACES][2] = {
    {-6.156629905886659149e-01, -8.396835231681325507e-01}, // face  0
    {-4.993481309458840389e-01, -7.554360723048078041e-01}, // face  1
    {+7.034312929482801069e-01, +4.320282052635449066e-01}, // face  2
    {+4.172973922766483046e-01, +9.684416900790995819e-02}, // face  3
    {-1.523209312100386459e-01, -4.674370376236925972e-01}, // face  4
    {+4.338080530902198029e-01, +7.048332979968887635e-01}, // face  5
    {+1.579652106524671029e-01, +4.724802355507352059e-01}, // face  6
    {-3.814083619040824491e-01, -5.781392172370660582e-02}, // face  7
    {-3.454444512157824332e-01, -1.923799155579705017e-02}, // face  8
    {+1.379372809046388315e-01, +4.545363861211293988e-01}, // face  9
    {-3.454444512157823777e-01, -6.335906582328775238e-01}, // face 10
    {+1.379372809046386927e-01, -1.938594276938917504e-01}, // face 11
    {+4.338080530902199694e-01, +1.149868628701303241e-01}, // face 12
    {+1.579652106524672972e-01, -1.739540475604785807e-01}, // face 13
    {-3.814083619040827822e-01, -6.629801308182394770e-01}, // face 14
    {+4.172973922766484156e-01, +6.917737757919307784e-01}, // face 15
    {-1.523209312100382851e-01, +1.795775351583079049e-01}, // face 16
    {-6.156629905886655818e-01, -3.238101657775167008e-01}, // face 17
    {-4.993481309458840944e-01, -1.882431935007105595e-01}, // face 18
    {+7.034312929482802179e-01, +8.973319844234353138e-01}, // face 19
};

/** @brief Definition of which faces neighbor each other. */
static const FaceOrientIJK faceNeighbors[NUM_ICOSA_FACES][4] = {
    {
        // face 0
        {0, {0, 0, 0}, 0}, // central face
        {4, {2, 0, 2}, 1}, // ij quadrant
        {1, {2, 2, 0}, 5}, // ki quadrant
        {5, {0, 2, 2}, 3}  // jk quadrant
    },
    {
        // face 1
        {1, {0, 0, 0}, 0}, // central face
        {0, {2, 0, 2}, 1}, // ij quadrant
        {2, {2, 2, 0}, 5}, // ki quadrant
        {6, {0, 2, 2}, 3}  // jk quadrant
    },
    {
        // face 2
        {2, {0, 0, 0}, 0}, // central face
        {1, {2, 0, 2}, 1}, // ij quadrant
        {3, {2, 2, 0}, 5}, // ki quadrant
        {7, {0, 2, 2}, 3}  // jk quadrant
    },
    {
        // face 3
        {3, {0, 0, 0}, 0}, // central face
        {2, {2, 0, 2}, 1}, // ij quadrant
        {4, {2, 2, 0}, 5}, // ki quadrant
        {8, {0, 2, 2}, 3}  // jk quadrant
    },
    {
        // face 4
        {4, {0, 0, 0}, 0}, // central face
        {3, {2, 0, 2}, 1}, // ij quadrant
        {0, {2, 2, 0}, 5}, // ki quadrant
        {9, {0, 2, 2}, 3}  // jk quadrant
    },
    {
        // face 5
        {5, {0, 0, 0}, 0},  // central face
        {10, {2, 2, 0}, 3}, // ij quadrant
        {14, {2, 0, 2}, 3}, // ki quadrant
        {0, {0, 2, 2}, 3}   // jk quadrant
    },
    {
        // face 6
        {6, {0, 0, 0}, 0},  // central face
        {11, {2, 2, 0}, 3}, // ij quadrant
        {10, {2, 0, 2}, 3}, // ki quadrant
        {1, {0, 2, 2}, 3}   // jk quadrant
    },
    {
        // face 7
        {7, {0, 0, 0}, 0},  // central face
        {12, {2, 2, 0}, 3}, // ij quadrant
        {11, {2, 0, 2}, 3}, // ki quadrant
        {2, {0, 2, 2}, 3}   // jk quadrant
    },
    {
        // face 8
        {8, {0, 0, 0}, 0},  // central face
        {13, {2, 2, 0}, 3}, // ij quadrant
        {12, {2, 0, 2}, 3}, // ki quadrant
        {3, {0, 2, 2}, 3}   // jk quadrant
    },
    {
        // face 9
        {9, {0, 0, 0}, 0},  // central face
        {14, {2, 2, 0}, 3}, // ij quadrant
        {13, {2, 0, 2}, 3}, // ki quadrant
        {4, {0, 2, 2}, 3}   // jk quadrant
    },
    {
        // face 10
        {10, {0, 0, 0}, 0}, // central face
        {5, {2, 2, 0}, 3},  // ij quadrant
        {6, {2, 0, 2}, 3},  // ki quadrant
        {15, {0, 2, 2}, 3}  // jk quadrant
    },
    {
        // face 11
        {11, {0, 0, 0}, 0}, // central face
        {6, {2, 2, 0}, 3},  // ij quadrant
        {7, {2, 0, 2}, 3},  // ki quadrant
        {16, {0, 2, 2}, 3}  // jk quadrant
    },
    {
        // face 12
        {12, {0, 0, 0}, 0}, // central face
        {7, {2, 2, 0}, 3},  // ij quadrant
        {8, {2, 0, 2}, 3},  // ki quadrant
        {17, {0, 2, 2}, 3}  // jk quadrant
    },
    {
        // face 13
        {13, {0, 0, 0}, 0}, // central face
        {8, {2, 2, 0}, 3},  // ij quadrant
        {9, {2, 0, 2}, 3},  // ki quadrant
        {18, {0, 2, 2}, 3}  // jk quadrant
    },
    {
        // face 14
        {14, {0, 0, 0}, 0}, // central face
        {9, {2, 2, 0}, 3},  // ij quadrant
        {5, {2, 0, 2}, 3},  // ki quadrant
        {19, {0, 2, 2}, 3}  // jk quadrant
    },
    {
        // face 15
        {15, {0, 0, 0}, 0}, // central face
        {16, {2, 0, 2}, 1}, // ij quadrant
        {19, {2, 2, 0}, 5}, // ki quadrant
        {10, {0, 2, 2}, 3}  // jk quadrant
    },
    {
        // face 16
        {16, {0, 0, 0}, 0}, // central face
        {17, {2, 0, 2}, 1}, // ij quadrant
        {15, {2, 2, 0}, 5}, // ki quadrant
        {11, {0, 2, 2}, 3}  // jk quadrant
    },
    {
        // face 17
        {17, {0, 0, 0}, 0}, // central face
        {18, {2, 0, 2}, 1}, // ij quadrant
        {16, {2, 2, 0}, 5}, // ki quadrant
        {12, {0, 2, 2}, 3}  // jk quadrant
    },
    {
        // face 18
        {18, {0, 0, 0}, 0}, // central face
        {19, {2, 0, 2}, 1}, // ij quadrant
        {17, {2, 2, 0}, 5}, // ki quadrant
        {13, {0, 2, 2}, 3}  // jk quadrant
    },
    {
        // face 19
        {19, {0, 0, 0}, 0}, // central face
        {15, {2, 0, 2}, 1}, // ij quadrant
        {18, {2, 2, 0}, 5}, // ki quadrant
        {14, {0, 2, 2}, 3}  // jk quadrant
    }};

/** @brief direction from the origin face to the destination face, relative to
 * the origin face's coordinate system, or -1 if not adjacent.
 */
static const int adjacentFaceDir[NUM_ICOSA_FACES][NUM_ICOSA_FACES] = {
    {0,  KI, -1, -1, IJ, JK, -1, -1, -1, -1,
     -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, // face 0
    {IJ, 0,  KI, -1, -1, -1, JK, -1, -1, -1,
     -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, // face 1
    {-1, IJ, 0,  KI, -1, -1, -1, JK, -1, -1,
     -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, // face 2
    {-1, -1, IJ, 0,  KI, -1, -1, -1, JK, -1,
     -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, // face 3
    {KI, -1, -1, IJ, 0,  -1, -1, -1, -1, JK,
     -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, // face 4
    {JK, -1, -1, -1, -1, 0,  -1, -1, -1, -1,
     IJ, -1, -1, -1, KI, -1, -1, -1, -1, -1}, // face 5
    {-1, JK, -1, -1, -1, -1, 0,  -1, -1, -1,
     KI, IJ, -1, -1, -1, -1, -1, -1, -1, -1}, // face 6
    {-1, -1, JK, -1, -1, -1, -1, 0,  -1, -1,
     -1, KI, IJ, -1, -1, -1, -1, -1, -1, -1}, // face 7
    {-1, -1, -1, JK, -1, -1, -1, -1, 0,  -1,
     -1, -1, KI, IJ, -1, -1, -1, -1, -1, -1}, // face 8
    {-1, -1, -1, -1, JK, -1, -1, -1, -1, 0,
     -1, -1, -1, KI, IJ, -1, -1, -1, -1, -1}, // face 9
    {-1, -1, -1, -1, -1, IJ, KI, -1, -1, -1,
     0,  -1, -1, -1, -1, JK, -1, -1, -1, -1}, // face 10
    {-1, -1, -1, -1, -1, -1, IJ, KI, -1, -1,
     -1, 0,  -1, -1, -1, -1, JK, -1, -1, -1}, // face 11
    {-1, -1, -1, -1, -1, -1, -1, IJ, KI, -1,
     -1, -1, 0,  -1, -1, -1, -1, JK, -1, -1}, // face 12
    {-1, -1, -1, -1, -1, -1, -1, -1, IJ, KI,
     -1, -1, -1, 0,  -1, -1, -1, -1, JK, -1}, // face 13
    {-1, -1, -1, -1, -1, KI, -1, -1, -1, IJ,
     -1, -1, -1, -1, 0,  -1, -1, -1, -1, JK}, // face 14
    {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
     JK, -1, -1, -1, -1, 0,  IJ, -1, -1, KI}, // face 15
    {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
     -1, JK, -1, -1, -1, KI, 0,  IJ, -1, -1}, // face 16
    {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
     -1, -1, JK, -1, -1, -1, KI, 0,  IJ, -1}, // face 17
    {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
     -1, -1, -1, JK, -1, -1, -1, KI, 0,  IJ}, // face 18
    {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
     -1, -1, -1, -1, JK, IJ, -1, -1, KI, 0} // face 19
};

/** @brief overage distance table */
const int maxDimByCIIres[] = {
    2,       // res  0
    -1,      // res  1
    14,      // res  2
    -1,      // res  3
    98,      // res  4
    -1,      // res  5
    686,     // res  6
    -1,      // res  7
    4802,    // res  8
    -1,      // res  9
    33614,   // res 10
    -1,      // res 11
    235298,  // res 12
    -1,      // res 13
    1647086, // res 14
    -1,      // res 15
    11529602 // res 16
};

/** @brief unit scale distance table */
static const int unitScaleByCIIres[] = {
    1,      // res  0
    -1,     // res  1
    7,      // res  2
    -1,     // res  3
    49,     // res  4
    -1,     // res  5
    343,    // res  6
    -1,     // res  7
    2401,   // res  8
    -1,     // res  9
    16807,  // res 10
    -1,     // res 11
    117649, // res 12
    -1,     // res 13
    823543, // res 14
    -1,     // res 15
    5764801 // res 16
};

// Forward declares to make diff nicer
// TODO: remove and reorder functions after landing
static void _vec3ToHex2d(const Vec3d *p, int res, int *face, Vec2d *v);
static void _vec3ToClosestFace(const Vec3d *v, int *face, double *sqd);

/**
 * Encodes a Vec3d coordinate to the FaceIJK address of the containing
 * cell at the specified resolution.
 *
 * Vec3d p is expected to be on the unit sphere.
 *
 * @param p The Vec3d coordinates to encode.
 * @param res The desired H3 resolution for the encoding.
 * @param h Output: FaceIJK address of the containing cell at resolution res.
 */
void _vec3ToFaceIjk(Vec3d p, int res, FaceIJK *h) {
    // first convert to hex2d
    Vec2d v;
    _vec3ToHex2d(&p, res, &h->face, &v);

    // then convert to ijk+
    _hex2dToCoordIJK(&v, &h->coord);
}

/**
 * Compute the local north and east directions on the tangent plane
 * at a point on the unit sphere.
 *
 * Will not work if p is at a pole, but icosahedron face centers
 * are never at the poles.
 *
 * @param p Unit vector on the sphere.
 * @param north Output: local north direction on tangent plane.
 * @param east Output: local east direction on tangent plane.
 */
/* `_vec3TangentBasis` retired: its only caller went through
 * `_vec3AzimuthCosSinRads` with p1 always equal to `faceCenterPoint[face]`,
 * so the basis is constant per face and now read from the precomputed
 * `faceNorthDir` / `faceEastDir` tables (declared above). The runtime
 * computation is preserved in scripts/dev/gen-face-tangent-basis.py
 * which generated those tables — re-run the script if any face center
 * changes. */

/* `_vec3AzimuthRads` retired: the only caller (`_vec3ToHex2d`) now
 * computes (cosAzim, sinAzim) directly via the face-indexed cos/sin
 * helper below.
 *
 * `_vec3AzimuthCosSinRads` retired: it called `_vec3TangentBasis(p1,
 * ...)` to compute (north, east) on the fly, but in `_vec3ToHex2d`
 * p1 is always `faceCenterPoint[face]` — a fixed point per face. The
 * precomputed `faceNorthDir[face]` / `faceEastDir[face]` tables
 * (declared above with the runtime tangent-basis as their definition)
 * give the same vectors as table lookups, eliminating the per-call
 * vec3LinComb + vec3Normalize + vec3Cross. The new
 * `_vec3FaceAzimuthCosSinRads` below is the face-indexed form. */
static inline void _vec3FaceAzimuthCosSinRads(int face, Vec3d p,
                                              double *cosAzim,
                                              double *sinAzim) {
    Vec3d p1 = faceCenterPoint[face];
    Vec3d northDir = faceNorthDir[face];
    Vec3d eastDir = faceEastDir[face];
    Vec3d pProj = vec3LinComb(1.0, p, -vec3Dot(p, p1), p1);
    vec3Normalize(&pProj);
    /* pProj is a unit vector in the tangent plane at p1, so its
     * components along (north, east) are themselves cos/sin of the
     * azimuth. nDot² + eDot² = 1 by construction (the third tangent
     * component is zero), so no `sqrt + divide` normalize needed. */
    *cosAzim = vec3Dot(pProj, northDir);
    *sinAzim = vec3Dot(pProj, eastDir);
}

/**
 * Encodes a coordinate on the sphere to the corresponding icosahedral face and
 * containing 2D hex coordinates relative to that face center.
 *
 * Vec3d p is expected to be on the unit sphere.
 *
 * @param p The Vec3d coordinates to encode.
 * @param res The desired H3 resolution for the encoding.
 * @param face Output: The icosahedral face containing the coordinates.
 * @param v Output: The 2D hex coordinates of the cell containing the point.
 */
static void _vec3ToHex2d(const Vec3d *p, int res, int *face, Vec2d *v) {
    // determine the icosahedron face
    double sqd;
    _vec3ToClosestFace(p, face, &sqd);

    /* cos(r) = 1 - 2*sin²(r/2) = 1 - sqd/2. We need r itself for the
     * downstream tan(r), so go via asin: acos(z) = π/2 - asin(z). The
     * |1 - sqd/2| ≤ 1 invariant holds because sqd is a squared distance
     * between two points on the unit sphere (sqd ∈ [0, 4]). */
    double r = M_PI_2 - approx_asin(1.0 - sqd * 0.5);

    if (r < EPSILON) {
        v->x = v->y = 0.0;
        return;
    }

    /* Algebraic theta computation. Original code did
     *     azim   = atan2(eDot, nDot)        (1 atan2)
     *     theta  = A - azim                  (where A = faceAxesAz[face][0])
     *     theta -= M_AP7_ROT_RADS  (Class III only)
     *     (cosTheta, sinTheta) = sincos(theta)        (1 sincos)
     * Replaced via the angle-subtraction identity:
     *     cos(A - B) = cos A cos B + sin A sin B
     *     sin(A - B) = sin A cos B - cos A sin B
     * with (cosAzim, sinAzim) read directly from p2Proj's tangent-plane
     * components (no atan2 needed) and (cos A, sin A) read from the
     * precomputed `faceAxesAzCosCII` / `faceAxesAzSinCII` tables that
     * already hold both the Class II and Class III variants per face.
     * Eliminates 1 atan2 + 1 sincos per encode call. */
    double cosAzim, sinAzim;
    _vec3FaceAzimuthCosSinRads(*face, *p, &cosAzim, &sinAzim);

    int rotIdx = isResolutionClassIII(res) ? 1 : 0;
    double cosA = faceAxesAzCosCII[*face][rotIdx];
    double sinA = faceAxesAzSinCII[*face][rotIdx];
    /* theta = A - azim  ⇒  cos/sin of theta directly from identity. */
    double cTheta = cosA * cosAzim + sinA * sinAzim;
    double sTheta = sinA * cosAzim - cosA * sinAzim;

    /* Gnomonic scaling: r = tan(r). Derive tan from one approx_sincos
     * call (saves a separate libm tan invocation): tan(r) = sin(r)/cos(r). */
    double sR, cR;
    approx_sincos(r, &sR, &cR);
    r = sR / cR;

    // scale for current resolution length u
    r *= INV_RES0_U_GNOMONIC;
    for (int i = 0; i < res; i++) {
        r *= M_SQRT7;
    }

    v->x = r * cTheta;
    v->y = r * sTheta;
}

/**
 * Determines the 3D coordinates of a cell given by 2D
 * hex coordinates on a particular icosahedral face.
 *
 * @param v The 2D hex coordinates of the cell.
 * @param face The icosahedral face upon which the 2D hex coordinate system is
 *             centered.
 * @param res The H3 resolution of the cell.
 * @param substrate Indicates whether or not this grid is actually a substrate
 *        grid relative to the specified resolution.
 * @param v3 Output: the 3D coordinates of the cell center point
 */
static void _hex2dToVec3(const Vec2d *v, int face, int res, int substrate,
                         Vec3d *v3) {
    // calculate (r, theta) in hex2d
    double r = _v2dMag(v);

    if (r < EPSILON) {
        *v3 = faceCenterPoint[face];
        return;
    }

    /* Combined resolution + substrate + classIII radial scaling via lookup
     * table. The loop `for (i=0; i<res; i++) r *= M_RSQRT7` becomes a
     * single load. The substrate branches similarly collapse — substrate-
     * classIII bumps the exponent by 1 (so we read RSQRT7_POW[res+1]) and
     * multiplies by M_ONETHIRD. Equivalence note: floating-point
     * multiplication is non-associative, so this can produce results that
     * differ from the per-iteration loop by ≤1 ULP. */
    double rScale;
    if (substrate) {
        int powIdx = isResolutionClassIII(res) ? res + 1 : res;
        rScale = RSQRT7_POW[powIdx] * M_ONETHIRD;
    } else {
        rScale = RSQRT7_POW[res];
    }
    double rScaled = r * rScale * RES0_U_GNOMONIC;

    /* perform inverse gnomonic scaling of r — approx_atan is ≤6 nm
     * absolute error vs. libm, well inside H3's 0.5 m budget. */
    double rOut = approx_atan(rScaled);

    /* Algebraic theta elimination. The original code did
     *   theta = atan2(v->y, v->x);
     *   if (!substrate && classIII) theta += M_AP7_ROT_RADS;
     *   theta = faceAz - theta;
     *   dir = vec3LinComb(cos(theta), northDir, sin(theta), eastDir);
     *
     * Since cos(atan2(y,x)) = x/r and sin(atan2(y,x)) = y/r exactly, and
     * the final theta is `A - theta_orig` for some per-face A (with A
     * picking up an optional `-M_AP7_ROT_RADS` for Class III), the angle
     * subtraction identity gives:
     *   cos(theta_final) = (cosA*x + sinA*y) / r
     *   sin(theta_final) = (sinA*x - cosA*y) / r
     * which uses only multiplications + adds + one division. Eliminates
     * 1×atan2 + 2×libm trig per call. cosA/sinA are precomputed in
     * faceAxesAzCosCII / faceAxesAzSinCII (above). */
    int rotIdx = (!substrate && isResolutionClassIII(res)) ? 1 : 0;
    double cosA = faceAxesAzCosCII[face][rotIdx];
    double sinA = faceAxesAzSinCII[face][rotIdx];
    double invR = 1.0 / r;
    double cosTheta = (cosA * v->x + sinA * v->y) * invR;
    double sinTheta = (sinA * v->x - cosA * v->y) * invR;

    /* Per-face tangent basis is invariant — replaces the per-call
     * _vec3TangentBasis(faceCenterPoint[face], ...) work with two
     * constant loads. */
    Vec3d northDir = faceNorthDir[face];
    Vec3d eastDir = faceEastDir[face];

    Vec3d dir = vec3LinComb(cosTheta, northDir, sinTheta, eastDir);

    /* approx_sincos: one polynomial pair for both rOut sin and cos.
     * cos(rOut) and sin(rOut) feed the final v3 placement on the
     * sphere; with rOut bounded in [0, π/2] (it's atan of a positive),
     * polynomial precision is ≤180 nm. */
    double sR, cR;
    approx_sincos(rOut, &sR, &cR);
    *v3 = vec3LinComb(cR, faceCenterPoint[face], sR, dir);
    vec3Normalize(v3);
}

#if defined(H3_HAS_NEON)
#include <arm_neon.h>

/**
 * Process 2 hex2dToVec3 conversions in lockstep via NEON 2-wide
 * doubles. All math is bit-equivalent (modulo ~1 ULP from FMA
 * reordering) to the scalar `_hex2dToVec3` above.
 *
 * Parametrized on `substrate` so the same kernel serves both
 * cellToBoundary's substrate=1 fan-out and cellsToLatLngs's
 * substrate=0 cell-center decode. Callers pass a compile-time
 * constant for `substrate`, which the compiler dead-eliminates the
 * other branch of.
 *
 * Equivalence is preserved by using the exact same algebraic
 * substitutions and polynomial coefficients as the scalar path.
 */
/* NEON 4-wide H3 digit walk. Processes 4 cells' digit chains in
 * lockstep through int32x4_t lanes, replacing the per-cell
 * `_h3ToFaceIjkWithInitializedFijk` inner loop. Pre-condition: caller
 * has seeded `ijk_i / ijk_j / ijk_k` with each cell's base-cell home
 * coords and verified res, non-pentagon, non-leading-5 invariants. The
 * primitive validated 2.97× over the scalar walk in
 * `benchmarkApproxLibm.c::neon4_digit_walk_N1024`.
 *
 * Lane mapping: cells[0..3] feed lanes 0..3 of the int32x4_t. Per
 * digit step:
 *   - extract digit r from each cell via vshlq_s64 (variable shift)
 *     + AND with 7, narrow to int32x4_t
 *   - matrix-multiply the (i, j, k) triple by the per-Class-r M_ap7
 *     transform via 3× vmlaq_n_s32
 *   - add UNIT_VECS[digit] component-wise via bit extraction
 *     (digit's bits 2/1/0 ARE the i/j/k components for digits 0..6)
 *   - normalize: subtract min(i,j,k) clamped to 0 from each lane.
 */
static inline void _digitWalkBatch4Neon(const H3Index *cells, int res,
                                        int32_t *ijk_i, int32_t *ijk_j,
                                        int32_t *ijk_k) {
    int64x2_t h0 = vld1q_s64((const int64_t *)&cells[0]);
    int64x2_t h1 = vld1q_s64((const int64_t *)&cells[2]);
    int32x4_t i = vld1q_s32(ijk_i);
    int32x4_t j = vld1q_s32(ijk_j);
    int32x4_t k = vld1q_s32(ijk_k);

    for (int r = 1; r <= res; r++) {
        int shift_amt = (MAX_H3_RES - r) * 3;
        int64x2_t shift_vec = vdupq_n_s64(-shift_amt);
        int64x2_t mask = vdupq_n_s64(7);
        int64x2_t d0 = vandq_s64(vshlq_s64(h0, shift_vec), mask);
        int64x2_t d1 = vandq_s64(vshlq_s64(h1, shift_vec), mask);
        int32x4_t digits = vcombine_s32(vmovn_s64(d0), vmovn_s64(d1));

        int32x4_t new_i, new_j, new_k;
        if (r & 1) {
            /* Class III (odd r): _downAp7_neighbor.
             *   new_i = 3*i + j ; new_j = 3*j + k ; new_k = i + 3*k */
            new_i = vmlaq_n_s32(j, i, 3);
            new_j = vmlaq_n_s32(k, j, 3);
            new_k = vmlaq_n_s32(i, k, 3);
        } else {
            /* Class II (even r): _downAp7r_neighbor.
             *   new_i = 3*i + k ; new_j = i + 3*j ; new_k = j + 3*k */
            new_i = vmlaq_n_s32(k, i, 3);
            new_j = vmlaq_n_s32(i, j, 3);
            new_k = vmlaq_n_s32(j, k, 3);
        }

        int32x4_t one = vdupq_n_s32(1);
        new_i = vaddq_s32(new_i, vandq_s32(vshrq_n_s32(digits, 2), one));
        new_j = vaddq_s32(new_j, vandq_s32(vshrq_n_s32(digits, 1), one));
        new_k = vaddq_s32(new_k, vandq_s32(digits, one));

        int32x4_t min_ij = vminq_s32(new_i, new_j);
        int32x4_t min_ijk = vminq_s32(min_ij, new_k);
        int32x4_t pos_min = vmaxq_s32(min_ijk, vdupq_n_s32(0));
        i = vsubq_s32(new_i, pos_min);
        j = vsubq_s32(new_j, pos_min);
        k = vsubq_s32(new_k, pos_min);
    }

    vst1q_s32(ijk_i, i);
    vst1q_s32(ijk_j, j);
    vst1q_s32(ijk_k, k);
}

static inline void _hex2dToVec3_pair(const Vec2d *v0, const Vec2d *v1,
                                     int face0, int face1, int res,
                                     int substrate, Vec3d *out0, Vec3d *out1) {
    /* Pack inputs into 2-wide lanes. */
    float64x2_t vx = {v0->x, v1->x};
    float64x2_t vy = {v0->y, v1->y};

    /* r = sqrt(x*x + y*y). */
    float64x2_t r = vsqrtq_f64(vfmaq_f64(vmulq_f64(vx, vx), vy, vy));

    /* rScale: substrate=1 bumps powIdx by 1 in classIII and folds in
     * M_ONETHIRD; substrate=0 just uses RSQRT7_POW[res]. */
    double rScale;
    if (substrate) {
        int powIdx = isResolutionClassIII(res) ? res + 1 : res;
        rScale = RSQRT7_POW[powIdx] * M_ONETHIRD * RES0_U_GNOMONIC;
    } else {
        rScale = RSQRT7_POW[res] * RES0_U_GNOMONIC;
    }
    float64x2_t rScaled = vmulq_f64(r, vdupq_n_f64(rScale));

    /* approx_atan(rScaled) via NEON 2-wide. */
    float64x2_t rOut = approx_atan_neon2(rScaled);

    /* approx_sincos(rOut). */
    float64x2_t sR, cR;
    approx_sincos_neon2(rOut, &sR, &cR);

    /* Algebraic theta. rotIdx selects the per-face cos/sin variant.
     *   substrate=1: rotIdx = 0 (substrate grid handles classIII).
     *   substrate=0: rotIdx = isClassIII ? 1 : 0. */
    int rotIdx = (!substrate && isResolutionClassIII(res)) ? 1 : 0;
    float64x2_t cosA = {faceAxesAzCosCII[face0][rotIdx],
                        faceAxesAzCosCII[face1][rotIdx]};
    float64x2_t sinA = {faceAxesAzSinCII[face0][rotIdx],
                        faceAxesAzSinCII[face1][rotIdx]};
    float64x2_t invR = vdivq_f64(vdupq_n_f64(1.0), r);
    float64x2_t cosTheta =
        vmulq_f64(vfmaq_f64(vmulq_f64(cosA, vx), sinA, vy), invR);
    float64x2_t sinTheta =
        vmulq_f64(vfmsq_f64(vmulq_f64(sinA, vx), cosA, vy), invR);

    /* Per-face tangent basis & center, packed by lane. */
    Vec3d nd0 = faceNorthDir[face0], nd1 = faceNorthDir[face1];
    Vec3d ed0 = faceEastDir[face0], ed1 = faceEastDir[face1];
    Vec3d fc0 = faceCenterPoint[face0], fc1 = faceCenterPoint[face1];
    float64x2_t ndx = {nd0.x, nd1.x};
    float64x2_t ndy = {nd0.y, nd1.y};
    float64x2_t ndz = {nd0.z, nd1.z};
    float64x2_t edx = {ed0.x, ed1.x};
    float64x2_t edy = {ed0.y, ed1.y};
    float64x2_t edz = {ed0.z, ed1.z};
    float64x2_t fcx = {fc0.x, fc1.x};
    float64x2_t fcy = {fc0.y, fc1.y};
    float64x2_t fcz = {fc0.z, fc1.z};

    /* dir = cosTheta * northDir + sinTheta * eastDir */
    float64x2_t dirX = vfmaq_f64(vmulq_f64(cosTheta, ndx), sinTheta, edx);
    float64x2_t dirY = vfmaq_f64(vmulq_f64(cosTheta, ndy), sinTheta, edy);
    float64x2_t dirZ = vfmaq_f64(vmulq_f64(cosTheta, ndz), sinTheta, edz);

    /* v3 = cR * faceCenter + sR * dir */
    float64x2_t v3x = vfmaq_f64(vmulq_f64(cR, fcx), sR, dirX);
    float64x2_t v3y = vfmaq_f64(vmulq_f64(cR, fcy), sR, dirY);
    float64x2_t v3z = vfmaq_f64(vmulq_f64(cR, fcz), sR, dirZ);

    /* Normalize each lane: norm = sqrt(x²+y²+z²); scale by 1/norm if > 0. */
    float64x2_t normSq =
        vfmaq_f64(vfmaq_f64(vmulq_f64(v3x, v3x), v3y, v3y), v3z, v3z);
    float64x2_t norm = vsqrtq_f64(normSq);
    uint64x2_t nonZero = vcgtq_f64(norm, vdupq_n_f64(0.0));
    float64x2_t inv =
        vbslq_f64(nonZero, vdivq_f64(vdupq_n_f64(1.0), norm), vdupq_n_f64(0.0));
    v3x = vmulq_f64(v3x, inv);
    v3y = vmulq_f64(v3y, inv);
    v3z = vmulq_f64(v3z, inv);

    /* EPSILON early-out: if r < EPSILON for a lane, replace its v3 with
     * faceCenterPoint[face].  Branchless via mask select. */
    uint64x2_t r_tiny = vcltq_f64(r, vdupq_n_f64(EPSILON));
    v3x = vbslq_f64(r_tiny, fcx, v3x);
    v3y = vbslq_f64(r_tiny, fcy, v3y);
    v3z = vbslq_f64(r_tiny, fcz, v3z);

    out0->x = vgetq_lane_f64(v3x, 0);
    out0->y = vgetq_lane_f64(v3y, 0);
    out0->z = vgetq_lane_f64(v3z, 0);
    out1->x = vgetq_lane_f64(v3x, 1);
    out1->y = vgetq_lane_f64(v3y, 1);
    out1->z = vgetq_lane_f64(v3z, 1);
}

/**
 * Batched vec3 → LatLng for 2 lanes via NEON 2-wide.
 * Uses approx_asin_neon2 + approx_atan2_neon2.
 */
static inline void _vec3_to_latlng_pair(const Vec3d *v0, const Vec3d *v1,
                                        LatLng *out0, LatLng *out1) {
    float64x2_t vx = {v0->x, v1->x};
    float64x2_t vy = {v0->y, v1->y};
    float64x2_t vz = {v0->z, v1->z};
    float64x2_t lat = approx_asin_neon2(vz);
    float64x2_t lng = approx_atan2_neon2(vy, vx);
    out0->lat = vgetq_lane_f64(lat, 0);
    out0->lng = vgetq_lane_f64(lng, 0);
    out1->lat = vgetq_lane_f64(lat, 1);
    out1->lng = vgetq_lane_f64(lng, 1);
}

#endif /* H3_HAS_NEON */

/* H3_HAS_AVX512 is force-cancelled at the top of this file when the TU
 * isn't compiled with -mavx512f (see comment up top). So this guard
 * resolves to TRUE only when AVX-512 intrinsics are actually usable
 * here. */
#if defined(H3_HAS_AVX512)
#include <immintrin.h>

/**
 * Process up to 8 hex2dToVec3 conversions in lockstep via AVX-512 8-wide
 * doubles. Used by `_faceIjkToCellBoundary` (count=6) and
 * `_faceIjkPentToCellBoundary` (count=5) on Intel hosts to fold all
 * cell vertices into a single SIMD call (vs NEON's 3 pairs).
 *
 * Parametrized on `substrate` so the same kernel serves both
 * cellToBoundary's substrate=1 fan-out and cellsToLatLngs's
 * substrate=0 cell-center decode. Callers pass a compile-time
 * constant for `substrate`, which the compiler dead-eliminates.
 * Same coefficients and algebraic substitutions as the scalar /
 * NEON path.
 *
 * `count` must be ≤ 8. Lanes [count..8) carry junk and are ignored
 * by the caller; the function is otherwise lane-uniform.
 */
static inline void _hex2dToVec3_x8_avx512(const Vec2d *v, const int *faces,
                                          int res, int substrate, int count,
                                          Vec3d *out) {
    /* Pack inputs (zeros in padding lanes for safety). */
    double xs[8] = {0}, ys[8] = {0};
    for (int i = 0; i < count; i++) {
        xs[i] = v[i].x;
        ys[i] = v[i].y;
    }
    __m512d vx = _mm512_loadu_pd(xs);
    __m512d vy = _mm512_loadu_pd(ys);

    /* r = sqrt(x*x + y*y). */
    __m512d r = _mm512_sqrt_pd(_mm512_fmadd_pd(vy, vy, _mm512_mul_pd(vx, vx)));

    /* rScale: substrate=1 bumps powIdx by 1 in classIII and folds in
     * M_ONETHIRD; substrate=0 just uses RSQRT7_POW[res]. */
    double rScale;
    if (substrate) {
        int powIdx = isResolutionClassIII(res) ? res + 1 : res;
        rScale = RSQRT7_POW[powIdx] * M_ONETHIRD * RES0_U_GNOMONIC;
    } else {
        rScale = RSQRT7_POW[res] * RES0_U_GNOMONIC;
    }
    __m512d rScaled = _mm512_mul_pd(r, _mm512_set1_pd(rScale));

    /* approx_atan(rScaled) via AVX-512 8-wide. */
    __m512d rOut = approx_atan_avx512(rScaled);

    /* approx_sincos(rOut). */
    __m512d sR, cR;
    approx_sincos_avx512(rOut, &sR, &cR);

    /* Algebraic theta. rotIdx selects the per-face cos/sin variant.
     *   substrate=1: rotIdx = 0 (substrate grid handles classIII).
     *   substrate=0: rotIdx = isClassIII ? 1 : 0. */
    int rotIdx = (!substrate && isResolutionClassIII(res)) ? 1 : 0;
    double cosA_arr[8] = {0}, sinA_arr[8] = {0};
    double ndx_arr[8] = {0}, ndy_arr[8] = {0}, ndz_arr[8] = {0};
    double edx_arr[8] = {0}, edy_arr[8] = {0}, edz_arr[8] = {0};
    double fcx_arr[8] = {0}, fcy_arr[8] = {0}, fcz_arr[8] = {0};
    for (int i = 0; i < count; i++) {
        int f = faces[i];
        cosA_arr[i] = faceAxesAzCosCII[f][rotIdx];
        sinA_arr[i] = faceAxesAzSinCII[f][rotIdx];
        ndx_arr[i] = faceNorthDir[f].x;
        ndy_arr[i] = faceNorthDir[f].y;
        ndz_arr[i] = faceNorthDir[f].z;
        edx_arr[i] = faceEastDir[f].x;
        edy_arr[i] = faceEastDir[f].y;
        edz_arr[i] = faceEastDir[f].z;
        fcx_arr[i] = faceCenterPoint[f].x;
        fcy_arr[i] = faceCenterPoint[f].y;
        fcz_arr[i] = faceCenterPoint[f].z;
    }
    __m512d cosA = _mm512_loadu_pd(cosA_arr);
    __m512d sinA = _mm512_loadu_pd(sinA_arr);
    __m512d ndx = _mm512_loadu_pd(ndx_arr);
    __m512d ndy = _mm512_loadu_pd(ndy_arr);
    __m512d ndz = _mm512_loadu_pd(ndz_arr);
    __m512d edx = _mm512_loadu_pd(edx_arr);
    __m512d edy = _mm512_loadu_pd(edy_arr);
    __m512d edz = _mm512_loadu_pd(edz_arr);
    __m512d fcx = _mm512_loadu_pd(fcx_arr);
    __m512d fcy = _mm512_loadu_pd(fcy_arr);
    __m512d fcz = _mm512_loadu_pd(fcz_arr);

    __m512d invR = _mm512_div_pd(_mm512_set1_pd(1.0), r);
    __m512d cosTheta =
        _mm512_mul_pd(_mm512_fmadd_pd(sinA, vy, _mm512_mul_pd(cosA, vx)), invR);
    __m512d sinTheta =
        _mm512_mul_pd(_mm512_fmsub_pd(sinA, vx, _mm512_mul_pd(cosA, vy)), invR);

    /* dir = cosTheta * northDir + sinTheta * eastDir */
    __m512d dirX = _mm512_fmadd_pd(sinTheta, edx, _mm512_mul_pd(cosTheta, ndx));
    __m512d dirY = _mm512_fmadd_pd(sinTheta, edy, _mm512_mul_pd(cosTheta, ndy));
    __m512d dirZ = _mm512_fmadd_pd(sinTheta, edz, _mm512_mul_pd(cosTheta, ndz));

    /* v3 = cR * faceCenter + sR * dir */
    __m512d v3x = _mm512_fmadd_pd(sR, dirX, _mm512_mul_pd(cR, fcx));
    __m512d v3y = _mm512_fmadd_pd(sR, dirY, _mm512_mul_pd(cR, fcy));
    __m512d v3z = _mm512_fmadd_pd(sR, dirZ, _mm512_mul_pd(cR, fcz));

    /* Normalize each lane. */
    __m512d normSq = _mm512_fmadd_pd(
        v3z, v3z, _mm512_fmadd_pd(v3y, v3y, _mm512_mul_pd(v3x, v3x)));
    __m512d norm = _mm512_sqrt_pd(normSq);
    __mmask8 nonZero =
        _mm512_cmp_pd_mask(norm, _mm512_setzero_pd(), _CMP_GT_OQ);
    __m512d inv = _mm512_mask_blend_pd(
        nonZero, _mm512_setzero_pd(), _mm512_div_pd(_mm512_set1_pd(1.0), norm));
    v3x = _mm512_mul_pd(v3x, inv);
    v3y = _mm512_mul_pd(v3y, inv);
    v3z = _mm512_mul_pd(v3z, inv);

    /* EPSILON early-out per lane. */
    __mmask8 r_tiny =
        _mm512_cmp_pd_mask(r, _mm512_set1_pd(EPSILON), _CMP_LT_OQ);
    v3x = _mm512_mask_blend_pd(r_tiny, v3x, fcx);
    v3y = _mm512_mask_blend_pd(r_tiny, v3y, fcy);
    v3z = _mm512_mask_blend_pd(r_tiny, v3z, fcz);

    /* Store back to scalar Vec3d outputs. */
    double v3x_arr[8], v3y_arr[8], v3z_arr[8];
    _mm512_storeu_pd(v3x_arr, v3x);
    _mm512_storeu_pd(v3y_arr, v3y);
    _mm512_storeu_pd(v3z_arr, v3z);
    for (int i = 0; i < count; i++) {
        out[i].x = v3x_arr[i];
        out[i].y = v3y_arr[i];
        out[i].z = v3z_arr[i];
    }
}

/**
 * Batched vec3 → LatLng for up to 8 lanes via AVX-512.
 * Uses approx_asin_avx512 + approx_atan2_avx512.
 */
static inline void _vec3_to_latlng_x8_avx512(const Vec3d *v, int count,
                                             LatLng *out) {
    double xs[8] = {0}, ys[8] = {0}, zs[8] = {0};
    for (int i = 0; i < count; i++) {
        xs[i] = v[i].x;
        ys[i] = v[i].y;
        zs[i] = v[i].z;
    }
    __m512d vx = _mm512_loadu_pd(xs);
    __m512d vy = _mm512_loadu_pd(ys);
    __m512d vz = _mm512_loadu_pd(zs);
    __m512d lat = approx_asin_avx512(vz);
    __m512d lng = approx_atan2_avx512(vy, vx);
    double lat_arr[8], lng_arr[8];
    _mm512_storeu_pd(lat_arr, lat);
    _mm512_storeu_pd(lng_arr, lng);
    for (int i = 0; i < count; i++) {
        out[i].lat = lat_arr[i];
        out[i].lng = lng_arr[i];
    }
}

#endif /* H3_HAS_AVX512 */

/**
 * Determines the center point in 3D coordinates of a cell given by
 * a FaceIJK address at a specified resolution.
 *
 * @param h The FaceIJK address of the cell.
 * @param res The H3 resolution of the cell.
 * @param g Output: The 3D coordinates of the cell center point.
 */
void _faceIjkToVec3(const FaceIJK *h, int res, Vec3d *g) {
    Vec2d v;
    _ijkToHex2d(&h->coord, &v);
    _hex2dToVec3(&v, h->face, res, 0, g);
}

/**
 * Generates the cell boundary in spherical coordinates for a pentagonal cell
 * given by a FaceIJK address at a specified resolution.
 *
 * @param h The FaceIJK address of the pentagonal cell.
 * @param res The H3 resolution of the cell.
 * @param start The first topological vertex to return.
 * @param length The number of topological vertexes to return.
 * @param g Output: The spherical coordinates of the cell boundary.
 */
void _faceIjkPentToCellBoundary(const FaceIJK *h, int res, int start,
                                int length, CellBoundary *g) {
    int adjRes = res;
    FaceIJK centerIJK = *h;
    FaceIJK fijkVerts[NUM_PENT_VERTS];
    _faceIjkPentToVerts(&centerIJK, &adjRes, fijkVerts);

    // If we're returning the entire loop, we need one more iteration in case
    // of a distortion vertex on the last edge
    int additionalIteration = length == NUM_PENT_VERTS ? 1 : 0;

    /* Pre-compute (Vec3d, LatLng) for all 5 main vertices via SIMD batching.
     * Dispatch order: AVX-512 single 8-wide call (Intel) > NEON 2 pairs +
     * scalar tail (AArch64) > scalar fallback. */
#if defined(H3_HAS_AVX512) || defined(H3_HAS_NEON)
    FaceIJK adjustedPent[NUM_PENT_VERTS];
    Vec3d preV3Pent[NUM_PENT_VERTS];
    LatLng preLatLngPent[NUM_PENT_VERTS];
    {
        /* Fast-path: if all 5 vertices are strictly inside the substrate
         * face (sum < maxDim*3), the overage adjustments are no-ops and
         * we skip them. The pentagon variant uses _adjustPentVertOverage
         * which iterates _adjustOverageClassII until no NEW_FACE — that's
         * a loop, so skipping it when unnecessary saves more than the
         * hex case. */
        int maxDim3Pent = maxDimByCIIres[adjRes] * 3;
        int allNoOverage = 1;
        for (int i = 0; i < NUM_PENT_VERTS; i++) {
            adjustedPent[i] = fijkVerts[i];
            int sum = adjustedPent[i].coord.i + adjustedPent[i].coord.j +
                      adjustedPent[i].coord.k;
            if (sum >= maxDim3Pent) {
                allNoOverage = 0;
            }
        }
        if (!allNoOverage) {
            for (int i = 0; i < NUM_PENT_VERTS; i++) {
                _adjustPentVertOverage(&adjustedPent[i], adjRes);
            }
        }
        Vec2d hex2d[NUM_PENT_VERTS];
        int faces[NUM_PENT_VERTS];
        for (int i = 0; i < NUM_PENT_VERTS; i++) {
            _ijkToHex2d(&adjustedPent[i].coord, &hex2d[i]);
            faces[i] = adjustedPent[i].face;
        }
#if defined(H3_HAS_AVX512)
        /* All 5 vertices fit in one __m512d (3 padding lanes). */
        _hex2dToVec3_x8_avx512(hex2d, faces, adjRes, /*substrate=*/1,
                               NUM_PENT_VERTS, preV3Pent);
        _vec3_to_latlng_x8_avx512(preV3Pent, NUM_PENT_VERTS, preLatLngPent);
#else /* H3_HAS_NEON */
        /* 2 NEON pairs cover vertices 0..3 */
        for (int i = 0; i + 2 <= NUM_PENT_VERTS; i += 2) {
            _hex2dToVec3_pair(&hex2d[i], &hex2d[i + 1], faces[i], faces[i + 1],
                              adjRes, /*substrate=*/1, &preV3Pent[i],
                              &preV3Pent[i + 1]);
            _vec3_to_latlng_pair(&preV3Pent[i], &preV3Pent[i + 1],
                                 &preLatLngPent[i], &preLatLngPent[i + 1]);
        }
        /* Vertex 4 (5th) — scalar fallback */
        _hex2dToVec3(&hex2d[NUM_PENT_VERTS - 1], faces[NUM_PENT_VERTS - 1],
                     adjRes, 1, &preV3Pent[NUM_PENT_VERTS - 1]);
        preLatLngPent[NUM_PENT_VERTS - 1] =
            vec3ToLatLng(preV3Pent[NUM_PENT_VERTS - 1]);
#endif
    }
#endif

    // convert each vertex to lat/lng
    // adjust the face of each vertex as appropriate and introduce
    // edge-crossing vertices as needed
    g->numVerts = 0;
    FaceIJK lastFijk = {0};
    for (int vert = start; vert < start + length + additionalIteration;
         vert++) {
        int v = vert % NUM_PENT_VERTS;

#if defined(H3_HAS_AVX512) || defined(H3_HAS_NEON)
        FaceIJK fijk = adjustedPent[v];
#else
        FaceIJK fijk = fijkVerts[v];

        _adjustPentVertOverage(&fijk, adjRes);
#endif

        // all Class III pentagon edges cross icosa edges
        // note that Class II pentagons have vertices on the edge,
        // not edge intersections
        if (isResolutionClassIII(res) && vert > start) {
            // find hex2d of the two vertexes on the last face

            FaceIJK tmpFijk = fijk;

            Vec2d orig2d0;
            _ijkToHex2d(&lastFijk.coord, &orig2d0);

            int currentToLastDir = adjacentFaceDir[tmpFijk.face][lastFijk.face];

            const FaceOrientIJK *fijkOrient =
                &faceNeighbors[tmpFijk.face][currentToLastDir];

            tmpFijk.face = fijkOrient->face;
            CoordIJK *ijk = &tmpFijk.coord;

            // rotate and translate for adjacent face (fused n-step)
            _ijkRotate60ccw_n(ijk, fijkOrient->ccwRot60);

            CoordIJK transVec = fijkOrient->translate;
            _ijkScale(&transVec, unitScaleByCIIres[adjRes] * 3);
            _ijkAdd(ijk, &transVec, ijk);
            _ijkNormalize(ijk);

            Vec2d orig2d1;
            _ijkToHex2d(ijk, &orig2d1);

            // find the appropriate icosa face edge vertexes
            int maxDim = maxDimByCIIres[adjRes];
            Vec2d v0 = {3.0 * maxDim, 0.0};
            Vec2d v1 = {-1.5 * maxDim, 3.0 * M_SQRT3_2 * maxDim};
            Vec2d v2 = {-1.5 * maxDim, -3.0 * M_SQRT3_2 * maxDim};

            Vec2d *edge0;
            Vec2d *edge1;
            switch (adjacentFaceDir[tmpFijk.face][fijk.face]) {
            case IJ:
                edge0 = &v0;
                edge1 = &v1;
                break;
            case JK:
                edge0 = &v1;
                edge1 = &v2;
                break;
            case KI:
            default:
                assert(adjacentFaceDir[tmpFijk.face][fijk.face] == KI);
                edge0 = &v2;
                edge1 = &v0;
                break;
            }

            // find the intersection and add the lat/lng point to the result
            Vec2d inter;
            _v2dIntersect(&orig2d0, &orig2d1, edge0, edge1, &inter);
            Vec3d v3;
            _hex2dToVec3(&inter, tmpFijk.face, adjRes, 1, &v3);
            g->verts[g->numVerts] = vec3ToLatLng(v3);
            g->numVerts++;
        }

        // convert vertex to lat/lng and add to the result
        // vert == start + NUM_PENT_VERTS is only used to test for possible
        // intersection on last edge
        if (vert < start + NUM_PENT_VERTS) {
#if defined(H3_HAS_AVX512) || defined(H3_HAS_NEON)
            /* Lookup from the pre-computed batched results. */
            g->verts[g->numVerts] = preLatLngPent[v];
#else
            Vec2d vec;
            _ijkToHex2d(&fijk.coord, &vec);
            Vec3d v3;
            _hex2dToVec3(&vec, fijk.face, adjRes, 1, &v3);
            g->verts[g->numVerts] = vec3ToLatLng(v3);
#endif
            g->numVerts++;
        }

        lastFijk = fijk;
    }
}

/**
 * Get the vertices of a pentagon cell as substrate FaceIJK addresses
 *
 * @param fijk The FaceIJK address of the cell.
 * @param res In/out: the H3 resolution of the cell, adjusted for substrate.
 * @param fijkVerts Output: array for the vertices.
 */
void _faceIjkPentToVerts(FaceIJK *fijk, int *res, FaceIJK *fijkVerts) {
    // `static const` keeps these tables in .rodata instead of being
    // copy-initialized on the stack on every call (see _faceIjkToVerts).
    // the vertexes of an origin-centered pentagon in a Class II resolution on a
    // substrate grid with aperture sequence 33r. The aperture 3 gets us the
    // vertices, and the 3r gets us back to Class II.
    // vertices listed ccw from the i-axes
    static const CoordIJK vertsCII[NUM_PENT_VERTS] = {
        {2, 1, 0}, // 0
        {1, 2, 0}, // 1
        {0, 2, 1}, // 2
        {0, 1, 2}, // 3
        {1, 0, 2}, // 4
    };

    // the vertexes of an origin-centered pentagon in a Class III resolution on
    // a substrate grid with aperture sequence 33r7r. The aperture 3 gets us the
    // vertices, and the 3r7r gets us to Class II. vertices listed ccw from the
    // i-axes
    static const CoordIJK vertsCIII[NUM_PENT_VERTS] = {
        {5, 4, 0}, // 0
        {1, 5, 0}, // 1
        {0, 5, 4}, // 2
        {0, 1, 5}, // 3
        {4, 0, 5}, // 4
    };

    // get the correct set of substrate vertices for this resolution
    const CoordIJK *verts;
    if (isResolutionClassIII(*res)) {
        verts = vertsCIII;
    } else {
        verts = vertsCII;
    }

    // adjust the center point to be in an aperture 33r substrate grid
    // these should be composed for speed
    _downAp3(&fijk->coord);
    _downAp3r(&fijk->coord);

    // if res is Class III we need to add a cw aperture 7 to get to
    // icosahedral Class II
    if (isResolutionClassIII(*res)) {
        _downAp7r(&fijk->coord);
        *res += 1;
    }

    // The center point is now in the same substrate grid as the origin
    // cell vertices. Add the center point substate coordinates
    // to each vertex to translate the vertices to that cell.
    for (int v = 0; v < NUM_PENT_VERTS; v++) {
        fijkVerts[v].face = fijk->face;
        _ijkAdd(&fijk->coord, &verts[v], &fijkVerts[v].coord);
        _ijkNormalize(&fijkVerts[v].coord);
    }
}

/**
 * Generates the cell boundary in spherical coordinates for a cell given by a
 * FaceIJK address at a specified resolution.
 *
 * @param h The FaceIJK address of the cell.
 * @param res The H3 resolution of the cell.
 * @param start The first topological vertex to return.
 * @param length The number of topological vertexes to return.
 * @param g Output: The spherical coordinates of the cell boundary.
 */
void _faceIjkToCellBoundary(const FaceIJK *h, int res, int start, int length,
                            CellBoundary *g) {
    int adjRes = res;
    FaceIJK centerIJK = *h;
    FaceIJK fijkVerts[NUM_HEX_VERTS];
    _faceIjkToVerts(&centerIJK, &adjRes, fijkVerts);

    // If we're returning the entire loop, we need one more iteration in case
    // of a distortion vertex on the last edge
    int additionalIteration = length == NUM_HEX_VERTS ? 1 : 0;

    /* Pre-compute (Vec3d, LatLng) for all 6 main vertices via SIMD batching.
     * The post-overage `fijk` per vertex is needed for both the SIMD batch
     * and the edge-crossing path's `lastFace`/`lastOverage` bookkeeping, so
     * we run the overage adjustment first into a local array, then batch
     * the trig math.
     *
     * Dispatch order: AVX-512 single 8-wide call (Intel) > NEON 3 pairs
     * (AArch64) > scalar fallback. */
#if defined(H3_HAS_AVX512) || defined(H3_HAS_NEON)
    FaceIJK adjusted[NUM_HEX_VERTS];
    Overage overages[NUM_HEX_VERTS];
    Vec3d preV3[NUM_HEX_VERTS];
    LatLng preLatLng[NUM_HEX_VERTS];
    {
        const int pentLeading4 = 0;
        /* Fast path for the common case: if every vertex's (i+j+k) is
         * strictly below maxDim*3 (substrate scale), no overage adjustment
         * is needed and we can skip the 6 _adjustOverageClassII calls
         * entirely. The interior of any icosahedral face has this property
         * — overages only occur when a vertex straddles a face edge,
         * which requires the cell to be near an edge or pentagon. */
        int maxDim3 = maxDimByCIIres[adjRes] * 3;
        int allNoOverage = 1;
        for (int i = 0; i < NUM_HEX_VERTS; i++) {
            adjusted[i] = fijkVerts[i];
            int sum =
                adjusted[i].coord.i + adjusted[i].coord.j + adjusted[i].coord.k;
            /* Strictly less ⇒ NO_OVERAGE. >= covers FACE_EDGE and NEW_FACE
             * which both require the slow path. */
            if (sum >= maxDim3) {
                allNoOverage = 0;
            }
        }
        if (allNoOverage) {
            for (int i = 0; i < NUM_HEX_VERTS; i++) {
                overages[i] = NO_OVERAGE;
            }
        } else {
            for (int i = 0; i < NUM_HEX_VERTS; i++) {
                overages[i] = _adjustOverageClassII(&adjusted[i], adjRes,
                                                    pentLeading4, 1);
            }
        }
        Vec2d hex2d[NUM_HEX_VERTS];
        int faces[NUM_HEX_VERTS];
        for (int i = 0; i < NUM_HEX_VERTS; i++) {
            _ijkToHex2d(&adjusted[i].coord, &hex2d[i]);
            faces[i] = adjusted[i].face;
        }
#if defined(H3_HAS_AVX512)
        /* All 6 vertices fit in one __m512d (2 padding lanes). */
        _hex2dToVec3_x8_avx512(hex2d, faces, adjRes, /*substrate=*/1,
                               NUM_HEX_VERTS, preV3);
        _vec3_to_latlng_x8_avx512(preV3, NUM_HEX_VERTS, preLatLng);
#else  /* H3_HAS_NEON */
        /* 3 NEON 2-wide pairs cover all 6 vertices. */
        for (int i = 0; i < NUM_HEX_VERTS; i += 2) {
            _hex2dToVec3_pair(&hex2d[i], &hex2d[i + 1], faces[i], faces[i + 1],
                              adjRes, /*substrate=*/1, &preV3[i],
                              &preV3[i + 1]);
            _vec3_to_latlng_pair(&preV3[i], &preV3[i + 1], &preLatLng[i],
                                 &preLatLng[i + 1]);
        }
#endif /* H3_HAS_AVX512 vs H3_HAS_NEON */
    }
#endif /* H3_HAS_AVX512 || H3_HAS_NEON */

    // convert each vertex to lat/lng
    // adjust the face of each vertex as appropriate and introduce
    // edge-crossing vertices as needed
    g->numVerts = 0;
    int lastFace = -1;
    Overage lastOverage = NO_OVERAGE;
    for (int vert = start; vert < start + length + additionalIteration;
         vert++) {
        int v = vert % NUM_HEX_VERTS;

#if defined(H3_HAS_AVX512) || defined(H3_HAS_NEON)
        FaceIJK fijk = adjusted[v];
        Overage overage = overages[v];
#else
        FaceIJK fijk = fijkVerts[v];

        const int pentLeading4 = 0;
        Overage overage = _adjustOverageClassII(&fijk, adjRes, pentLeading4, 1);
#endif

        /*
        Check for edge-crossing. Each face of the underlying icosahedron is a
        different projection plane. So if an edge of the hexagon crosses an
        icosahedron edge, an additional vertex must be introduced at that
        intersection point. Then each half of the cell edge can be projected
        to geographic coordinates using the appropriate icosahedron face
        projection. Note that Class II cell edges have vertices on the face
        edge, with no edge line intersections.
        */
        if (isResolutionClassIII(res) && vert > start &&
            fijk.face != lastFace && lastOverage != FACE_EDGE) {
            // find hex2d of the two vertexes on original face
            int lastV = (v + 5) % NUM_HEX_VERTS;
            Vec2d orig2d0;
            _ijkToHex2d(&fijkVerts[lastV].coord, &orig2d0);

            Vec2d orig2d1;
            _ijkToHex2d(&fijkVerts[v].coord, &orig2d1);

            // find the appropriate icosa face edge vertexes
            int maxDim = maxDimByCIIres[adjRes];
            Vec2d v0 = {3.0 * maxDim, 0.0};
            Vec2d v1 = {-1.5 * maxDim, 3.0 * M_SQRT3_2 * maxDim};
            Vec2d v2 = {-1.5 * maxDim, -3.0 * M_SQRT3_2 * maxDim};

            int face2 = ((lastFace == centerIJK.face) ? fijk.face : lastFace);
            Vec2d *edge0;
            Vec2d *edge1;
            switch (adjacentFaceDir[centerIJK.face][face2]) {
            case IJ:
                edge0 = &v0;
                edge1 = &v1;
                break;
            case JK:
                edge0 = &v1;
                edge1 = &v2;
                break;
            // case KI:
            default:
                assert(adjacentFaceDir[centerIJK.face][face2] == KI);
                edge0 = &v2;
                edge1 = &v0;
                break;
            }

            // find the intersection and add the lat/lng point to the result
            Vec2d inter;
            _v2dIntersect(&orig2d0, &orig2d1, edge0, edge1, &inter);
            /*
            If a point of intersection occurs at a hexagon vertex, then each
            adjacent hexagon edge will lie completely on a single icosahedron
            face, and no additional vertex is required.
            */
            bool isIntersectionAtVertex = _v2dAlmostEquals(&orig2d0, &inter) ||
                                          _v2dAlmostEquals(&orig2d1, &inter);
            if (!isIntersectionAtVertex) {
                Vec3d v3;
                _hex2dToVec3(&inter, centerIJK.face, adjRes, 1, &v3);
                g->verts[g->numVerts] = vec3ToLatLng(v3);
                g->numVerts++;
            }
        }

        // convert vertex to lat/lng and add to the result
        // vert == start + NUM_HEX_VERTS is only used to test for possible
        // intersection on last edge
        if (vert < start + NUM_HEX_VERTS) {
#if defined(H3_HAS_AVX512) || defined(H3_HAS_NEON)
            /* Lookup from the pre-computed batched results. */
            g->verts[g->numVerts] = preLatLng[v];
#else
            Vec2d vec;
            _ijkToHex2d(&fijk.coord, &vec);
            Vec3d v3;
            _hex2dToVec3(&vec, fijk.face, adjRes, 1, &v3);
            g->verts[g->numVerts] = vec3ToLatLng(v3);
#endif
            g->numVerts++;
        }

        lastFace = fijk.face;
        lastOverage = overage;
    }
}

/**
 * Bulk decode N cells to lat/lng centers via batched SIMD machinery.
 *
 * Two-stage pipeline:
 *   Stage 1 (per cell, scalar): _h3ToFaceIjk to get the FaceIJK address
 *           plus the cell's hex2d coordinates and face. The H3 digit
 *           walk is integer-heavy and inherently sequential per cell;
 *           there's no cross-cell dependency so the loop is naturally
 *           pipelinable.
 *   Stage 2 (across cells, SIMD): _hex2dToVec3 + vec3ToLatLng batched
 *           in groups of 8 (AVX-512), 2 (NEON), or 1 (scalar tail).
 *           Same-res precondition lets the rScale / rotIdx params be
 *           constant across the whole batch.
 *
 * Mixed-res input falls back to per-cell cellToLatLng. The split keeps
 * the API safe for any input but rewards bulk callers (polygonToCells,
 * gridDisk, etc. always produce same-res output) with the SIMD path.
 */
#define H3_CELLS_BATCH_STACK_THRESHOLD 64

H3Error H3_EXPORT(cellsToLatLngs)(const H3Index *cells, int64_t n,
                                  LatLng *out) {
    if (n <= 0) {
        return E_SUCCESS;
    }

    /* Same-res precondition check (one pass). */
    int firstRes = H3_GET_RESOLUTION(cells[0]);
    int sameRes = 1;
    for (int64_t i = 1; i < n; i++) {
        if (H3_GET_RESOLUTION(cells[i]) != firstRes) {
            sameRes = 0;
            break;
        }
    }

    if (!sameRes || n < 4) {
        /* Mixed res or tiny batch — per-cell scalar path is cheaper than
         * SIMD overhead. */
        for (int64_t i = 0; i < n; i++) {
            H3Error e = H3_EXPORT(cellToLatLng)(cells[i], &out[i]);
            if (e) {
                return e;
            }
        }
        return E_SUCCESS;
    }

    /* Same-res fast path with SIMD batching. */
    Vec2d stackHex2d[H3_CELLS_BATCH_STACK_THRESHOLD];
    int stackFaces[H3_CELLS_BATCH_STACK_THRESHOLD];
    Vec3d stackV3[H3_CELLS_BATCH_STACK_THRESHOLD];

    Vec2d *hex2d;
    int *faces;
    Vec3d *v3s;
    if (n <= H3_CELLS_BATCH_STACK_THRESHOLD) {
        hex2d = stackHex2d;
        faces = stackFaces;
        v3s = stackV3;
    } else {
        hex2d = H3_MEMORY(malloc)(n * sizeof(Vec2d));
        faces = H3_MEMORY(malloc)(n * sizeof(int));
        v3s = H3_MEMORY(malloc)(n * sizeof(Vec3d));
        if (!hex2d || !faces || !v3s) {
            if (hex2d) {
                H3_MEMORY(free)(hex2d);
            }
            if (faces) {
                H3_MEMORY(free)(faces);
            }
            if (v3s) {
                H3_MEMORY(free)(v3s);
            }
            return E_MEMORY_ALLOC;
        }
    }

    /* Stage 1: H3 → FaceIJK → (hex2d, face) per cell.
     *
     * On AArch64/NEON we batch the digit walk inside
     * `_h3ToFaceIjkWithInitializedFijk` 4 cells at a time via
     * `_digitWalkBatch4Neon` (validated 2.97× speedup on the inner
     * loop in `benchmarkApproxLibm.c`). The wrapping pre-pass / post-
     * pass stays scalar so we keep correct pentagon-leading-5
     * pre-rotation and overage handling per cell. Cells that fail the
     * SIMD-eligibility checks (pentagon base cell, leading-5
     * digit, or post-walk overage need) fall back to the scalar
     * `_h3ToFaceIjk` for that one cell.
     *
     * With H3_ENABLE_OPENMP the batch-of-4 outer loop parallelizes
     * across cores. Errors propagate via shared `err` flag. */
    H3Error err = E_SUCCESS;
#if defined(H3_HAS_NEON)
    int64_t numBatches = n / 4;
    H3_OMP_PARALLEL_FOR_LARGE(numBatches)
    for (int64_t b = 0; b < numBatches; b++) {
        if (err) {
            continue;
        }
        int64_t base = b * 4;
        /* Zero-init per gcc-ARM `-Werror=maybe-uninitialized`: when the
         * pre-pass below `continue`s before assigning a slot (cell
         * disqualified for SIMD), the slot is never read in the
         * `eligibleAll` branch, but gcc's flow analysis can't prove
         * it. Static-init sidesteps the warning at zero runtime cost. */
        H3Index group[4] = {0};
        int32_t gi[4] = {0}, gj[4] = {0}, gk[4] = {0};
        int gFaces[4] = {0};
        int eligibleAll = 1;

        /* Pre-pass: per-cell SIMD-eligibility check. SIMD path requires
         * all four cells to have:
         *   (a) valid base cell index
         *   (b) non-pentagon base cell
         *   (c) leading non-zero digit != 5 (no _h3Rotate60cw needed)
         *   (d) home FaceIJK at (0,0,0) — `possibleOverage == 0`
         *       precondition in `_h3ToFaceIjkWithInitializedFijk`,
         *       which means the post-walk ijk is the final answer
         *       with no overage handling required.
         * If any of (b)-(d) fails, the batch falls back to scalar
         * `_h3ToFaceIjk` which handles all cases correctly. */
        for (int j = 0; j < 4; j++) {
            H3Index h = cells[base + j];
            int bc = H3_GET_BASE_CELL(h);
            if (NEVER(bc < 0) || bc >= NUM_BASE_CELLS) {
                H3_OMP_ATOMIC_WRITE
                err = E_CELL_INVALID;
                eligibleAll = 0;
                break;
            }
            if (_isBaseCellPentagon(bc) || _h3LeadingNonZeroDigit(h) == 5) {
                eligibleAll = 0;
                continue;
            }
            int homeI = baseCellData[bc].homeFijk.coord.i;
            int homeJ = baseCellData[bc].homeFijk.coord.j;
            int homeK = baseCellData[bc].homeFijk.coord.k;
            if (homeI | homeJ | homeK) {
                /* Non-(0,0,0) home means possibleOverage == 1; defer
                 * to scalar `_h3ToFaceIjk` which runs the overage
                 * adjustment chain. */
                eligibleAll = 0;
                continue;
            }
            group[j] = h;
            gi[j] = homeI;
            gj[j] = homeJ;
            gk[j] = homeK;
            gFaces[j] = baseCellData[bc].homeFijk.face;
        }
        if (err) {
            continue;
        }

        if (eligibleAll) {
            /* All 4 cells eligible: SIMD digit walk produces the final
             * post-walk ijk for each. */
            _digitWalkBatch4Neon(group, firstRes, gi, gj, gk);
            for (int j = 0; j < 4; j++) {
                CoordIJK c = {gi[j], gj[j], gk[j]};
                _ijkToHex2d(&c, &hex2d[base + j]);
                faces[base + j] = gFaces[j];
            }
        } else {
            /* Mixed batch: fall back to scalar for all 4 cells.
             * Avoids running the SIMD walk and discarding its output
             * for the cells that need overage handling — the wasted
             * work is more expensive than the SIMD savings. */
            for (int j = 0; j < 4; j++) {
                FaceIJK fijk;
                H3Error e = _h3ToFaceIjk(cells[base + j], &fijk);
                if (e) {
                    H3_OMP_ATOMIC_WRITE
                    err = e;
                    continue;
                }
                _ijkToHex2d(&fijk.coord, &hex2d[base + j]);
                faces[base + j] = fijk.face;
            }
        }
    }
    if (err) {
        goto cleanup;
    }

    /* Tail: scalar path for the leftover < 4 cells. */
    H3_OMP_PARALLEL_FOR_LARGE(n)
    for (int64_t i = numBatches * 4; i < n; i++) {
        if (err) {
            continue;
        }
        FaceIJK fijk;
        H3Error e = _h3ToFaceIjk(cells[i], &fijk);
        if (e) {
            H3_OMP_ATOMIC_WRITE
            err = e;
            continue;
        }
        _ijkToHex2d(&fijk.coord, &hex2d[i]);
        faces[i] = fijk.face;
    }
    if (err) {
        goto cleanup;
    }
#else
    /* Non-NEON path: scalar per-cell loop. */
    H3_OMP_PARALLEL_FOR_LARGE(n)
    for (int64_t i = 0; i < n; i++) {
        if (err) {
            continue;
        }
        FaceIJK fijk;
        H3Error e = _h3ToFaceIjk(cells[i], &fijk);
        if (e) {
            H3_OMP_ATOMIC_WRITE
            err = e;
            continue;
        }
        _ijkToHex2d(&fijk.coord, &hex2d[i]);
        faces[i] = fijk.face;
    }
    if (err) {
        goto cleanup;
    }
#endif

    /* Stage 2a: hex2d → Vec3d via SIMD batches (substrate=0). */
    int64_t i = 0;
#if defined(H3_HAS_AVX512)
    while (i + 8 <= n) {
        _hex2dToVec3_x8_avx512(&hex2d[i], &faces[i], firstRes,
                               /*substrate=*/0, 8, &v3s[i]);
        i += 8;
    }
    if (i < n) {
        _hex2dToVec3_x8_avx512(&hex2d[i], &faces[i], firstRes,
                               /*substrate=*/0, (int)(n - i), &v3s[i]);
        i = n;
    }
#elif defined(H3_HAS_NEON)
    while (i + 2 <= n) {
        _hex2dToVec3_pair(&hex2d[i], &hex2d[i + 1], faces[i], faces[i + 1],
                          firstRes, /*substrate=*/0, &v3s[i], &v3s[i + 1]);
        i += 2;
    }
#endif
    /* Scalar tail. */
    for (; i < n; i++) {
        _hex2dToVec3(&hex2d[i], faces[i], firstRes, /*substrate=*/0, &v3s[i]);
    }

    /* Stage 2b: Vec3d → LatLng via SIMD batches. */
    i = 0;
#if defined(H3_HAS_AVX512)
    while (i + 8 <= n) {
        _vec3_to_latlng_x8_avx512(&v3s[i], 8, &out[i]);
        i += 8;
    }
    if (i < n) {
        _vec3_to_latlng_x8_avx512(&v3s[i], (int)(n - i), &out[i]);
        i = n;
    }
#elif defined(H3_HAS_NEON)
    while (i + 2 <= n) {
        _vec3_to_latlng_pair(&v3s[i], &v3s[i + 1], &out[i], &out[i + 1]);
        i += 2;
    }
#endif
    for (; i < n; i++) {
        out[i] = vec3ToLatLng(v3s[i]);
    }

cleanup:
    if (n > H3_CELLS_BATCH_STACK_THRESHOLD) {
        H3_MEMORY(free)(hex2d);
        H3_MEMORY(free)(faces);
        H3_MEMORY(free)(v3s);
    }
    return err;
}

/**
 * Bulk decode N cells to boundaries via cross-cell SoA SIMD batching.
 *
 * Single-cell `cellToBoundary` already runs its own 6-vertex fan-out
 * through SIMD (NEON 2-wide pairs / AVX-512 single 8-wide call). The
 * bulk path here gathers ALL 6N hex-cell vertices into flat SoA scratch
 * arrays so a single trig batch can stride across cells, giving full
 * SIMD lane utilization on AVX-512 (eliminating the 2 padding lanes
 * per cell of the single-cell path) and tighter memory access patterns
 * on NEON.
 *
 * Pipeline:
 *   Stage A — per-cell scalar:  _h3IsPentagon classify; _h3ToFaceIjk
 *             + _faceIjkToVerts for hex cells. Pentagon cells are
 *             tagged for per-cell fallback at Stage D.
 *   Stage B — per-vertex scalar: _adjustOverageClassII (with the same
 *             all-no-overage fast-path the single-cell path uses) and
 *             _ijkToHex2d + face into the SoA scratch. Pentagon slots
 *             are zero-initialized so the wide SIMD batch can stride
 *             over them harmlessly.
 *   Stage C — cross-cell SIMD: ONE big hex2d→Vec3d→LatLng batch over
 *             all 6N entries. AVX-512 8-wide / NEON 2-wide / scalar
 *             tail. Same-res precondition keeps `adjRes` constant
 *             across the whole batch.
 *   Stage D — per-cell post-pass: hex cells assemble CellBoundary from
 *             precomputed adjusted FaceIJK + overage + LatLng (with
 *             the existing edge-crossing detection logic from
 *             _faceIjkToCellBoundary). Pentagon cells call the
 *             scalar single-cell `cellToBoundary` path.
 *
 * Falls back to a per-cell loop for n < 8 (SIMD-setup overhead loss)
 * or mixed-resolution input (the SIMD batch's `rScale`/`adjRes`
 * params would not be uniform across the batch).
 *
 * Honors the `H3_MEMORY` allocator hooks; one heap allocation per
 * call, freed before return.
 */
H3Error H3_EXPORT(cellsToBoundaries)(const H3Index *cells, int64_t n,
                                     CellBoundary *out) {
    if (n <= 0) {
        return E_SUCCESS;
    }

    /* Same-res precondition + small-batch fallback. */
    int res0 = H3_GET_RESOLUTION(cells[0]);
    int sameRes = 1;
    for (int64_t i = 1; i < n; i++) {
        if (H3_GET_RESOLUTION(cells[i]) != res0) {
            sameRes = 0;
            break;
        }
    }
    if (!sameRes || n < 8) {
        for (int64_t i = 0; i < n; i++) {
            H3Error e = H3_EXPORT(cellToBoundary)(cells[i], &out[i]);
            if (e) {
                return e;
            }
        }
        return E_SUCCESS;
    }

    /* Single heap allocation for all SoA scratch. Layout: contiguous
     * sub-blocks so we can index each by base pointer. */
    int64_t scratchV = n * NUM_HEX_VERTS;
    FaceIJK *fijkVerts = H3_MEMORY(calloc)((size_t)scratchV, sizeof(FaceIJK));
    FaceIJK *adjusted = H3_MEMORY(calloc)((size_t)scratchV, sizeof(FaceIJK));
    Overage *overages = H3_MEMORY(calloc)((size_t)scratchV, sizeof(Overage));
    Vec2d *hex2d = H3_MEMORY(calloc)((size_t)scratchV, sizeof(Vec2d));
    int *faces = H3_MEMORY(calloc)((size_t)scratchV, sizeof(int));
    Vec3d *preV3 = H3_MEMORY(calloc)((size_t)scratchV, sizeof(Vec3d));
    LatLng *preLatLng = H3_MEMORY(calloc)((size_t)scratchV, sizeof(LatLng));
    FaceIJK *centerIJKs = H3_MEMORY(calloc)((size_t)n, sizeof(FaceIJK));
    char *isPent = H3_MEMORY(calloc)((size_t)n, sizeof(char));

    if (!fijkVerts || !adjusted || !overages || !hex2d || !faces || !preV3 ||
        !preLatLng || !centerIJKs || !isPent) {
        H3_MEMORY(free)(fijkVerts);
        H3_MEMORY(free)(adjusted);
        H3_MEMORY(free)(overages);
        H3_MEMORY(free)(hex2d);
        H3_MEMORY(free)(faces);
        H3_MEMORY(free)(preV3);
        H3_MEMORY(free)(preLatLng);
        H3_MEMORY(free)(centerIJKs);
        H3_MEMORY(free)(isPent);
        return E_MEMORY_ALLOC;
    }

    int adjRes = isResolutionClassIII(res0) ? res0 + 1 : res0;
    int maxDim3 = maxDimByCIIres[adjRes] * 3;

    H3Error err = E_SUCCESS;

    /* Stages A+B — fused per-cell scalar prep (hex cells only). The
     * fused pass keeps each cell's `fijkVerts[i*6 .. i*6+5]` slot in the
     * L1 cache between writing it (A) and reading it back to compute
     * adjusted/overage/hex2d (B), eliminating a round-trip through L2
     * for the 6N substrate-vertex array. Pentagons stay zero-initialized
     * so Stage C's strided SIMD batch sees harmless sentinel data
     * (face=0, hex2d=0). Parallel-for-safe: each iteration writes to
     * disjoint slots; errors propagate via shared `err` + atomic write. */
    H3_OMP_PARALLEL_FOR_LARGE(n)
    for (int64_t i = 0; i < n; i++) {
        if (_h3IsPentagon(cells[i])) {
            isPent[i] = 1;
            continue;
        }
        FaceIJK fijk;
        H3Error e = _h3ToFaceIjk(cells[i], &fijk);
        if (e) {
            H3_OMP_ATOMIC_WRITE
            err = e;
            continue;
        }
        centerIJKs[i] = fijk;
        FaceIJK *vs = &fijkVerts[i * NUM_HEX_VERTS];
        int tmpRes = res0;
        _faceIjkToVerts(&fijk, &tmpRes, vs);

        /* Stage B inlined: while vs is still in L1, compute adjusted /
         * overage / hex2d / faces for the same cell. */
        FaceIJK *adj = &adjusted[i * NUM_HEX_VERTS];
        Overage *ov = &overages[i * NUM_HEX_VERTS];
        int allNoOverage = 1;
        for (int v = 0; v < NUM_HEX_VERTS; v++) {
            adj[v] = vs[v];
            int sum = adj[v].coord.i + adj[v].coord.j + adj[v].coord.k;
            if (sum >= maxDim3) {
                allNoOverage = 0;
            }
        }
        if (allNoOverage) {
            for (int v = 0; v < NUM_HEX_VERTS; v++) {
                ov[v] = NO_OVERAGE;
            }
        } else {
            for (int v = 0; v < NUM_HEX_VERTS; v++) {
                ov[v] = _adjustOverageClassII(&adj[v], adjRes,
                                              /*pentLeading4=*/0,
                                              /*substrate=*/1);
            }
        }
        for (int v = 0; v < NUM_HEX_VERTS; v++) {
            _ijkToHex2d(&adj[v].coord, &hex2d[i * NUM_HEX_VERTS + v]);
            faces[i * NUM_HEX_VERTS + v] = adj[v].face;
        }
    }
    if (err) {
        goto cleanup;
    }

    /* Stage C — cross-cell SIMD batch: hex2d → Vec3d → LatLng. The
     * batch strides over all 6N entries (hex + pentagon-sentinel
     * slots). Output for pentagon slots is harmless; Stage D ignores
     * it via the per-cell pentagon fallback. */
    int64_t totalV = scratchV;
    int64_t i = 0;
#if defined(H3_HAS_AVX512)
    while (i + 8 <= totalV) {
        _hex2dToVec3_x8_avx512(&hex2d[i], &faces[i], adjRes,
                               /*substrate=*/1, 8, &preV3[i]);
        _vec3_to_latlng_x8_avx512(&preV3[i], 8, &preLatLng[i]);
        i += 8;
    }
    if (i < totalV) {
        int rem = (int)(totalV - i);
        _hex2dToVec3_x8_avx512(&hex2d[i], &faces[i], adjRes,
                               /*substrate=*/1, rem, &preV3[i]);
        _vec3_to_latlng_x8_avx512(&preV3[i], rem, &preLatLng[i]);
        i = totalV;
    }
#elif defined(H3_HAS_NEON)
    while (i + 2 <= totalV) {
        _hex2dToVec3_pair(&hex2d[i], &hex2d[i + 1], faces[i], faces[i + 1],
                          adjRes, /*substrate=*/1, &preV3[i], &preV3[i + 1]);
        _vec3_to_latlng_pair(&preV3[i], &preV3[i + 1], &preLatLng[i],
                             &preLatLng[i + 1]);
        i += 2;
    }
#endif
    /* Scalar tail (covers leftover pair on NEON; covers everything on
     * platforms with no SIMD primitives). */
    for (; i < totalV; i++) {
        _hex2dToVec3(&hex2d[i], faces[i], adjRes, /*substrate=*/1, &preV3[i]);
        preLatLng[i] = vec3ToLatLng(preV3[i]);
    }

    /* Stage D — per-cell boundary assembly. Hex cells use the
     * precomputed arrays + the same edge-crossing detection logic as
     * _faceIjkToCellBoundary. Pentagon cells fall back to per-cell.
     * Parallel-for-safe: out[cellI] writes are disjoint per iteration. */
    H3_OMP_PARALLEL_FOR_LARGE(n)
    for (int64_t cellI = 0; cellI < n; cellI++) {
        if (err) {
            continue; /* Short-circuit if any earlier iter errored. */
        }
        if (isPent[cellI]) {
            H3Error pe = H3_EXPORT(cellToBoundary)(cells[cellI], &out[cellI]);
            if (pe) {
                H3_OMP_ATOMIC_WRITE
                err = pe;
            }
            continue;
        }
        FaceIJK centerIJK = centerIJKs[cellI];
        FaceIJK *vs = &fijkVerts[cellI * NUM_HEX_VERTS];
        FaceIJK *adj = &adjusted[cellI * NUM_HEX_VERTS];
        Overage *ov = &overages[cellI * NUM_HEX_VERTS];
        LatLng *pll = &preLatLng[cellI * NUM_HEX_VERTS];
        CellBoundary *g = &out[cellI];
        g->numVerts = 0;
        int lastFace = -1;
        Overage lastOverage = NO_OVERAGE;
        /* +1 iteration handles a possible distortion vertex on the
         * last edge (mirrors the additionalIteration tail in
         * _faceIjkToCellBoundary). */
        for (int vert = 0; vert < NUM_HEX_VERTS + 1; vert++) {
            int v = vert % NUM_HEX_VERTS;
            FaceIJK fijk = adj[v];
            Overage overage = ov[v];

            if (isResolutionClassIII(res0) && vert > 0 &&
                fijk.face != lastFace && lastOverage != FACE_EDGE) {
                int lastV = (v + 5) % NUM_HEX_VERTS;
                Vec2d orig2d0;
                _ijkToHex2d(&vs[lastV].coord, &orig2d0);
                Vec2d orig2d1;
                _ijkToHex2d(&vs[v].coord, &orig2d1);

                int maxDim = maxDimByCIIres[adjRes];
                Vec2d v0 = {3.0 * maxDim, 0.0};
                Vec2d v1 = {-1.5 * maxDim, 3.0 * M_SQRT3_2 * maxDim};
                Vec2d v2 = {-1.5 * maxDim, -3.0 * M_SQRT3_2 * maxDim};

                int face2 =
                    ((lastFace == centerIJK.face) ? fijk.face : lastFace);
                Vec2d *edge0;
                Vec2d *edge1;
                switch (adjacentFaceDir[centerIJK.face][face2]) {
                case IJ:
                    edge0 = &v0;
                    edge1 = &v1;
                    break;
                case JK:
                    edge0 = &v1;
                    edge1 = &v2;
                    break;
                default:
                    edge0 = &v2;
                    edge1 = &v0;
                    break;
                }
                Vec2d inter;
                _v2dIntersect(&orig2d0, &orig2d1, edge0, edge1, &inter);
                bool isIntersectionAtVertex =
                    _v2dAlmostEquals(&orig2d0, &inter) ||
                    _v2dAlmostEquals(&orig2d1, &inter);
                if (!isIntersectionAtVertex) {
                    Vec3d v3;
                    _hex2dToVec3(&inter, centerIJK.face, adjRes,
                                 /*substrate=*/1, &v3);
                    g->verts[g->numVerts] = vec3ToLatLng(v3);
                    g->numVerts++;
                }
            }
            if (vert < NUM_HEX_VERTS) {
                g->verts[g->numVerts] = pll[v];
                g->numVerts++;
            }
            lastFace = fijk.face;
            lastOverage = overage;
        }
    }

cleanup:
    H3_MEMORY(free)(fijkVerts);
    H3_MEMORY(free)(adjusted);
    H3_MEMORY(free)(overages);
    H3_MEMORY(free)(hex2d);
    H3_MEMORY(free)(faces);
    H3_MEMORY(free)(preV3);
    H3_MEMORY(free)(preLatLng);
    H3_MEMORY(free)(centerIJKs);
    H3_MEMORY(free)(isPent);
    return err;
}

/**
 * Get the vertices of a cell as substrate FaceIJK addresses
 *
 * @param fijk The FaceIJK address of the cell.
 * @param res In/out: the H3 resolution of the cell, adjusted for substrate.
 * @param fijkVerts Output: array for the vertices.
 */
void _faceIjkToVerts(FaceIJK *fijk, int *res, FaceIJK *fijkVerts) {
    // the vertexes of an origin-centered cell in a Class II resolution on a
    // substrate grid with aperture sequence 33r. The aperture 3 gets us the
    // vertices, and the 3r gets us back to Class II.
    // vertices listed ccw from the i-axes.
    // `static const` keeps these in .rodata instead of being copy-initialized
    // onto the stack on every call (the function is called once per
    // cellToBoundary; stack churn was visible in the profile).
    static const CoordIJK vertsCII[NUM_HEX_VERTS] = {
        {2, 1, 0}, // 0
        {1, 2, 0}, // 1
        {0, 2, 1}, // 2
        {0, 1, 2}, // 3
        {1, 0, 2}, // 4
        {2, 0, 1}  // 5
    };

    // the vertexes of an origin-centered cell in a Class III resolution on a
    // substrate grid with aperture sequence 33r7r. The aperture 3 gets us the
    // vertices, and the 3r7r gets us to Class II.
    // vertices listed ccw from the i-axes
    static const CoordIJK vertsCIII[NUM_HEX_VERTS] = {
        {5, 4, 0}, // 0
        {1, 5, 0}, // 1
        {0, 5, 4}, // 2
        {0, 1, 5}, // 3
        {4, 0, 5}, // 4
        {5, 0, 1}  // 5
    };

    // get the correct set of substrate vertices for this resolution
    const CoordIJK *verts;
    if (isResolutionClassIII(*res)) {
        verts = vertsCIII;
    } else {
        verts = vertsCII;
    }

    // adjust the center point to be in an aperture 33r substrate grid
    // these should be composed for speed
    _downAp3(&fijk->coord);
    _downAp3r(&fijk->coord);

    // if res is Class III we need to add a cw aperture 7 to get to
    // icosahedral Class II
    if (isResolutionClassIII(*res)) {
        _downAp7r(&fijk->coord);
        *res += 1;
    }

    // The center point is now in the same substrate grid as the origin
    // cell vertices. Add the center point substate coordinates
    // to each vertex to translate the vertices to that cell.
    for (int v = 0; v < NUM_HEX_VERTS; v++) {
        fijkVerts[v].face = fijk->face;
        _ijkAdd(&fijk->coord, &verts[v], &fijkVerts[v].coord);
        _ijkNormalize(&fijkVerts[v].coord);
    }
}

/**
 * Adjusts a FaceIJK address in place so that the resulting cell address is
 * relative to the correct icosahedral face.
 *
 * @param fijk The FaceIJK address of the cell.
 * @param res The H3 resolution of the cell.
 * @param pentLeading4 Whether or not the cell is a pentagon with a leading
 *        digit 4.
 * @param substrate Whether or not the cell is in a substrate grid.
 * @return 0 if on original face (no overage); 1 if on face edge (only occurs
 *         on substrate grids); 2 if overage on new face interior
 */
Overage _adjustOverageClassII(FaceIJK *fijk, int res, int pentLeading4,
                              int substrate) {
    Overage overage = NO_OVERAGE;

    CoordIJK *ijk = &fijk->coord;

    // get the maximum dimension value; scale if a substrate grid
    int maxDim = maxDimByCIIres[res];
    if (substrate) {
        maxDim *= 3;
    }

    // check for overage
    if (substrate && ijk->i + ijk->j + ijk->k == maxDim) { // on edge
        overage = FACE_EDGE;
    } else if (ijk->i + ijk->j + ijk->k > maxDim) // overage
    {
        overage = NEW_FACE;

        const FaceOrientIJK *fijkOrient;
        if (ijk->k > 0) {
            if (ijk->j > 0) { // jk "quadrant"
                fijkOrient = &faceNeighbors[fijk->face][JK];
            } else // ik "quadrant"
            {
                fijkOrient = &faceNeighbors[fijk->face][KI];

                // adjust for the pentagonal missing sequence
                if (pentLeading4) {
                    // translate origin to center of pentagon
                    CoordIJK origin;
                    _setIJK(&origin, maxDim, 0, 0);
                    CoordIJK tmp;
                    _ijkSub(ijk, &origin, &tmp);
                    // rotate to adjust for the missing sequence
                    _ijkRotate60cw(&tmp);
                    // translate the origin back to the center of the triangle
                    _ijkAdd(&tmp, &origin, ijk);
                }
            }
        } else { // ij "quadrant"
            fijkOrient = &faceNeighbors[fijk->face][IJ];
        }

        fijk->face = fijkOrient->face;

        // rotate and translate for adjacent face (fused n-step)
        _ijkRotate60ccw_n(ijk, fijkOrient->ccwRot60);

        CoordIJK transVec = fijkOrient->translate;
        int unitScale = unitScaleByCIIres[res];
        if (substrate) {
            unitScale *= 3;
        }
        _ijkScale(&transVec, unitScale);
        _ijkAdd(ijk, &transVec, ijk);
        _ijkNormalize(ijk);

        // overage points on pentagon boundaries can end up on edges
        if (substrate && ijk->i + ijk->j + ijk->k == maxDim) { // on edge
            overage = FACE_EDGE;
        }
    }

    return overage;
}

/**
 * Adjusts a FaceIJK address for a pentagon vertex in a substrate grid in
 * place so that the resulting cell address is relative to the correct
 * icosahedral face.
 *
 * @param fijk The FaceIJK address of the cell.
 * @param res The H3 resolution of the cell.
 */
Overage _adjustPentVertOverage(FaceIJK *fijk, int res) {
    int pentLeading4 = 0;
    Overage overage;
    do {
        overage = _adjustOverageClassII(fijk, res, pentLeading4, 1);
    } while (overage == NEW_FACE);
    return overage;
}

/**
 * Encodes a coordinate on the sphere to the corresponding icosahedral face and
 * containing the squared euclidean distance to that face center.
 *
 * Vec3d v is expected to be on the unit sphere.
 *
 * @param v The Vec3d coordinates to encode.
 * @param face Output: The icosahedral face containing the coordinates.
 * @param sqd Output: The squared euclidean distance to its face center.
 */
static void _vec3ToClosestFace(const Vec3d *v, int *face, double *sqd) {
    /* Two-pass formulation: compute all 20 squared distances first (no
     * inter-iteration data dependency, so the compiler can issue FMAs in
     * parallel and auto-vectorize), then do a tight argmin scan. The
     * original interleaved compare-and-update created a serial dependency
     * on `*sqd` that pinned the loop to ~1 sqd per cycle on out-of-order
     * cores. */
    double sqds[NUM_ICOSA_FACES];
    double vx = v->x;
    double vy = v->y;
    double vz = v->z;
    for (int f = 0; f < NUM_ICOSA_FACES; ++f) {
        double dx = faceCenterPoint[f].x - vx;
        double dy = faceCenterPoint[f].y - vy;
        double dz = faceCenterPoint[f].z - vz;
        sqds[f] = dx * dx + dy * dy + dz * dz;
    }
    int minF = 0;
    double minSqd = sqds[0];
    for (int f = 1; f < NUM_ICOSA_FACES; ++f) {
        if (sqds[f] < minSqd) {
            minF = f;
            minSqd = sqds[f];
        }
    }
    *face = minF;
    *sqd = minSqd;
}
