"""
Database-backed session store using ORM and PostgreSQL UNLOGGED tables.

UNLOGGED tables skip WAL writes, making them ideal for ephemeral data
like sessions, cache, and rate limits. Sessions persist across app
restarts but are lost on PostgreSQL crash (acceptable for session data).

Multiple app servers coordinate via the shared PostgreSQL table.
Table DDL is generated by ``hyper setup`` from the ``HyperSession`` model.

Usage:
    store = DatabaseSessionStore(max_age=86400)

    # Use with SessionAuth middleware
    app.use(SessionAuth(secret="key", store=store, token_engine=engine))
"""

import secrets
from datetime import UTC, datetime, timedelta

from hyperdjango.auth.sessions import _SESSION_HASH_KEY
from hyperdjango.mixins import TimestampMixin
from hyperdjango.models import Field, Model
from hyperdjango.native import fast_json_loads

# ── Session Model ─────────────────────────────────────────────────────────


class HyperSession(TimestampMixin, Model):
    """ORM-backed session model.

    Table created by ``hyper setup`` as UNLOGGED (no WAL, fast writes).
    The ``data`` column is JSONB — pg.zig auto-parses to native Python dicts
    on read, no manual ``json.loads`` needed.
    """

    class Meta:
        table = "hyper_sessions"
        unlogged = True

    session_id: str = Field(primary_key=True)
    data: dict = Field(default={})
    user_id: int | None = Field(default=None, index=True)
    session_hash: str = Field(default="")
    expires_at: datetime | None = Field(default=None, index=True)


# ── Session Store ─────────────────────────────────────────────────────────


class DatabaseSessionStore:
    """PostgreSQL UNLOGGED session store backed by the HyperSession ORM model.

    All CRUD goes through the ORM QuerySet API. Table DDL is generated by
    ``hyper setup`` from the ``HyperSession`` model definition — no manual
    table creation needed.

    pg.zig returns JSONB ``data`` as native Python dicts (no json.loads).
    UNLOGGED tables skip WAL writes for fast ephemeral data.
    Multiple app servers coordinate via the shared PostgreSQL table.

    Features:
    - Session hash: invalidate all sessions on password change
    - Lazy cleanup: expired sessions filtered on access
    - Periodic cleanup: call cleanup() from a background task
    - User session invalidation: invalidate_for_user(user_id)
    """

    def __init__(self, max_age: int = 86400):
        self.max_age = max_age
        self._is_async = True

    def _expires_at(self) -> datetime:
        """Compute expiry timestamp from now + max_age."""
        return datetime.now(UTC) + timedelta(seconds=self.max_age)

    async def create(self, data: dict) -> str:
        """Create a new session. Returns session ID."""
        session_id = secrets.token_urlsafe(32)
        user_id = data.get("user_id") or data.get("id")
        # SessionAuth stores the auth hash under _SESSION_HASH_KEY
        # ("_session_auth_hash"). Reading the wrong key ("_session_hash") left
        # the session_hash column permanently empty, so invalidate_by_hash's
        # `.exclude(session_hash=valid_hash)` matched EVERY row and deleted all
        # of a user's sessions on any password change (over-deletion). Use the
        # canonical key so the column is populated and invalidation is precise.
        session_hash = data.get(_SESSION_HASH_KEY, "")

        session = HyperSession(
            session_id=session_id,
            data=data,
            user_id=user_id,
            session_hash=session_hash,
            expires_at=self._expires_at(),
        )
        await session.save()
        return session_id

    async def get(self, session_id: str) -> dict | None:
        """Get session data by ID. Returns None if expired or missing."""
        now = datetime.now(UTC)
        session = await HyperSession.objects.filter(
            session_id=session_id,
            expires_at__gt=now,
        ).first()
        if session is None:
            return None
        # pg.zig returns JSONB as native Python dict
        raw = session.data
        if isinstance(raw, dict):
            return raw
        if isinstance(raw, str):
            return fast_json_loads(raw)
        return None

    async def update(self, session_id: str, data: dict):
        """Update session data and extend expiry."""
        await HyperSession.objects.filter(session_id=session_id).update(
            data=data,
            expires_at=self._expires_at(),
        )

    async def delete(self, session_id: str):
        """Delete a session."""
        await HyperSession.objects.filter(session_id=session_id).delete()

    async def cleanup(self):
        """Delete all expired sessions. Call periodically."""
        now = datetime.now(UTC)
        await HyperSession.objects.filter(expires_at__lt=now).delete()

    async def count(self) -> int:
        """Count active (non-expired) sessions."""
        now = datetime.now(UTC)
        return await HyperSession.objects.filter(expires_at__gt=now).count()

    async def invalidate_for_user(self, user_id):
        """Invalidate all sessions for a user (log out everywhere)."""
        await HyperSession.objects.filter(user_id=user_id).delete()

    async def invalidate_by_hash(self, user_id, valid_hash: str):
        """Invalidate sessions where the session hash doesn't match.

        Used for session auth hash verification: when a user changes
        their password, generate a new session hash. All sessions with
        the old hash are invalidated.
        """
        await (
            HyperSession.objects.filter(
                user_id=user_id,
            )
            .exclude(
                session_hash=valid_hash,
            )
            .delete()
        )

    async def get_user_sessions(self, user_id) -> list[dict]:
        """Get all active sessions for a user."""
        now = datetime.now(UTC)
        sessions = (
            await HyperSession.objects.filter(
                user_id=user_id,
                expires_at__gt=now,
            )
            .order_by("-created_at")
            .all()
        )
        return [
            {
                "session_id": s.session_id,
                "data": s.data,
                "created_at": s.created_at,
                "expires_at": s.expires_at,
            }
            for s in sessions
        ]

    async def touch(self, session_id: str):
        """Extend session expiry without changing data."""
        await HyperSession.objects.filter(session_id=session_id).update(
            expires_at=self._expires_at(),
        )
