#!/usr/bin/env python3
"""
Live database integration tests for PostgreSQL extensions (hyperdjango.postgres).

Runs actual SQL against a real PostgreSQL database to verify that the SQL
generated by the postgres module works correctly.

Requires a running PostgreSQL instance. Connection URL is read from
HYPER_TEST_DATABASE_URL or defaults to postgres://localhost/hyperdjango_test.

Usage:
    uv run hyper-test postgres_ext_live
"""

# hyper-test: db_isolated

import asyncio
import json
import os
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from hyperdjango.database import Database
from hyperdjango.postgres import (
    ArrayField,
    BrinIndex,
    BTreeIndex,
    ExclusionConstraint,
    GinIndex,
    GistIndex,
    HashIndex,
    SpGistIndex,
)

PASS = 0
FAIL = 0
SUFFIX = f"_{int(time.time())}_{os.getpid()}"


def test(name, got, expected):
    global PASS, FAIL
    if got == expected:
        PASS += 1
    else:
        FAIL += 1
        print(f"  FAIL: {name}")
        print(f"    got:      {got!r}")
        print(f"    expected: {expected!r}")


def test_true(name, condition, detail=""):
    global PASS, FAIL
    if condition:
        PASS += 1
    else:
        FAIL += 1
        msg = f"  FAIL: {name}"
        if detail:
            msg += f" -- {detail}"
        print(msg)


async def setup_extensions(db):
    """Enable required PostgreSQL extensions."""
    await db.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    await db.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")


# ---------------------------------------------------------------------------
# ArrayField Tests
# ---------------------------------------------------------------------------


async def test_array_field(db):
    print("\n--- ArrayField (live) ---")
    tbl = f"test_arrays{SUFFIX}"
    try:
        await db.execute(f"""
            CREATE TABLE {tbl} (
                id SERIAL PRIMARY KEY,
                int_arr integer[],
                txt_arr text[],
                bool_arr boolean[]
            )
        """)

        # INSERT array values
        await db.execute(
            f"INSERT INTO {tbl} (int_arr, txt_arr, bool_arr) VALUES ($1, $2, $3)",
            [1, 2, 3],
            ["hello", "world"],
            [True, False],
        )
        await db.execute(
            f"INSERT INTO {tbl} (int_arr, txt_arr, bool_arr) VALUES ($1, $2, $3)",
            [4, 5],
            ["foo"],
            [True, True],
        )
        await db.execute(
            f"INSERT INTO {tbl} (int_arr, txt_arr, bool_arr) VALUES ($1, $2, $3)",
            [1, 5, 9],
            ["bar", "baz"],
            [False, False],
        )

        # SELECT all
        rows = await db.query(f"SELECT * FROM {tbl} ORDER BY id")
        test("array insert count", len(rows), 3)

        # array_contains (@>) -- rows where int_arr contains {1, 2}
        rows = await db.query(
            f"SELECT id FROM {tbl} WHERE int_arr @> $1 ORDER BY id", [1, 2]
        )
        test("array_contains @>", [r["id"] for r in rows], [1])

        # array_contained_by (<@) -- rows where int_arr is subset of {1,2,3,4,5}
        rows = await db.query(
            f"SELECT id FROM {tbl} WHERE int_arr <@ $1 ORDER BY id", [1, 2, 3, 4, 5]
        )
        test("array_contained_by <@", [r["id"] for r in rows], [1, 2])

        # array_overlap (&&) -- rows where int_arr overlaps with {5, 9}
        rows = await db.query(
            f"SELECT id FROM {tbl} WHERE int_arr && $1 ORDER BY id", [5, 9]
        )
        test("array_overlap &&", [r["id"] for r in rows], [2, 3])

        # array_append
        await db.execute(
            f"UPDATE {tbl} SET int_arr = array_append(int_arr, $1) WHERE id = $2", 99, 1
        )
        row = await db.query_one(f"SELECT int_arr FROM {tbl} WHERE id = 1")
        test("array_append", row["int_arr"], [1, 2, 3, 99])

        # array_prepend
        await db.execute(
            f"UPDATE {tbl} SET int_arr = array_prepend($1, int_arr) WHERE id = $2", 0, 2
        )
        row = await db.query_one(f"SELECT int_arr FROM {tbl} WHERE id = 2")
        test("array_prepend", row["int_arr"], [0, 4, 5])

        # array_length
        row = await db.query_one(
            f"SELECT array_length(int_arr, 1) AS len FROM {tbl} WHERE id = 1"
        )
        test("array_length", row["len"], 4)

        # array indexing (1-based)
        row = await db.query_one(
            f"SELECT int_arr[1] AS first, int_arr[2] AS second FROM {tbl} WHERE id = 1"
        )
        test("array_index [1]", row["first"], 1)
        test("array_index [2]", row["second"], 2)

        # array_remove
        await db.execute(
            f"UPDATE {tbl} SET int_arr = array_remove(int_arr, $1) WHERE id = $2", 99, 1
        )
        row = await db.query_one(f"SELECT int_arr FROM {tbl} WHERE id = 1")
        test("array_remove", row["int_arr"], [1, 2, 3])

        # array_position
        row = await db.query_one(
            f"SELECT array_position(int_arr, $1) AS pos FROM {tbl} WHERE id = 3", 9
        )
        test("array_position", row["pos"], 3)

        # NULL handling in arrays
        await db.execute(f"INSERT INTO {tbl} (int_arr) VALUES ($1)", None)
        row = await db.query_one(f"SELECT int_arr FROM {tbl} WHERE id = 4")
        test("array NULL", row["int_arr"], None)

        # Empty array
        await db.execute(f"INSERT INTO {tbl} (int_arr) VALUES ($1)", [])
        row = await db.query_one(f"SELECT int_arr FROM {tbl} WHERE id = 5")
        test("empty array", row["int_arr"], [])

        # array_cat (concatenate)
        row = await db.query_one(
            "SELECT array_cat($1::integer[], $2::integer[]) AS combined",
            [1, 2],
            [3, 4],
        )
        test("array_cat", row["combined"], [1, 2, 3, 4])

        # unnest
        rows = await db.query(
            f"SELECT unnest(int_arr) AS val FROM {tbl} WHERE id = 1 ORDER BY val"
        )
        test("unnest", [r["val"] for r in rows], [1, 2, 3])

        # text array operations
        rows = await db.query(f"SELECT id FROM {tbl} WHERE txt_arr @> $1", ["hello"])
        test("text array contains", [r["id"] for r in rows], [1])

        # boolean array
        row = await db.query_one(f"SELECT bool_arr FROM {tbl} WHERE id = 2")
        test("boolean array", row["bool_arr"], [True, True])

    finally:
        await db.execute(f"DROP TABLE IF EXISTS {tbl}")


# ---------------------------------------------------------------------------
# Full-Text Search Tests
# ---------------------------------------------------------------------------


async def test_full_text_search(db):
    print("\n--- Full-Text Search (live) ---")
    tbl = f"test_fts{SUFFIX}"
    try:
        await db.execute(f"""
            CREATE TABLE {tbl} (
                id SERIAL PRIMARY KEY,
                title TEXT NOT NULL,
                body TEXT NOT NULL,
                search_vec tsvector
            )
        """)

        # Insert test documents
        docs = [
            (
                "PostgreSQL Full Text",
                "PostgreSQL provides full text search capabilities with ranking",
            ),
            (
                "Python Programming",
                "Python is a versatile programming language used worldwide",
            ),
            (
                "Database Indexing",
                "Proper indexing improves database query performance significantly",
            ),
            (
                "Web Development",
                "Modern web development involves many programming frameworks",
            ),
            (
                "Search Optimization",
                "Search engine optimization improves website visibility and ranking",
            ),
        ]
        for title, body in docs:
            await db.execute(
                f"INSERT INTO {tbl} (title, body, search_vec) VALUES ($1, $2, to_tsvector('english', $1 || ' ' || $2))",
                title,
                body,
            )

        # to_tsvector + plainto_tsquery
        rows = await db.query(
            f"SELECT id, title FROM {tbl} WHERE search_vec @@ plainto_tsquery('english', $1) ORDER BY id",
            "programming",
        )
        test("plainto_tsquery 'programming'", len(rows), 2)
        test("fts finds python", rows[0]["title"], "Python Programming")
        test("fts finds web dev", rows[1]["title"], "Web Development")

        # SearchRank ordering
        rows = await db.query(
            f"""SELECT title, ts_rank(search_vec, plainto_tsquery('english', $1)) AS rank
                FROM {tbl}
                WHERE search_vec @@ plainto_tsquery('english', $1)
                ORDER BY rank DESC""",
            "search ranking",
        )
        test("rank ordering count", len(rows), 2)
        # Both "PostgreSQL Full Text" (ranking) and "Search Optimization" (search, ranking) match
        titles = [r["title"] for r in rows]
        test_true(
            "rank results contain search optimization", "Search Optimization" in titles
        )

        # Phrase search (phraseto_tsquery)
        rows = await db.query(
            f"SELECT title FROM {tbl} WHERE search_vec @@ phraseto_tsquery('english', $1)",
            "full text search",
        )
        test("phrase search", len(rows), 1)
        test("phrase search result", rows[0]["title"], "PostgreSQL Full Text")

        # Prefix search (raw tsquery with :*)
        rows = await db.query(
            f"SELECT title FROM {tbl} WHERE search_vec @@ to_tsquery('english', $1) ORDER BY id",
            "program:*",
        )
        test("prefix search count", len(rows), 2)

        # AND operator (raw tsquery)
        rows = await db.query(
            f"SELECT title FROM {tbl} WHERE search_vec @@ to_tsquery('english', $1)",
            "database & index",
        )
        test("AND search", len(rows), 1)
        test("AND search result", rows[0]["title"], "Database Indexing")

        # OR operator
        rows = await db.query(
            f"SELECT title FROM {tbl} WHERE search_vec @@ to_tsquery('english', $1) ORDER BY id",
            "python | web",
        )
        test("OR search count", len(rows), 2)

        # NOT operator
        rows = await db.query(
            f"SELECT title FROM {tbl} WHERE search_vec @@ to_tsquery('english', $1) ORDER BY id",
            "programming & !python",
        )
        test("NOT search", len(rows), 1)
        test("NOT search result", rows[0]["title"], "Web Development")

        # websearch_to_tsquery
        rows = await db.query(
            f"SELECT title FROM {tbl} WHERE search_vec @@ websearch_to_tsquery('english', $1) ORDER BY id",
            "database OR python",
        )
        test("websearch OR", len(rows), 2)

        # ts_headline
        row = await db.query_one(
            f"""SELECT ts_headline('english', body, plainto_tsquery('english', $1),
                    'StartSel=<b>, StopSel=</b>, MaxWords=35, MinWords=15') AS headline
                FROM {tbl} WHERE id = 1""",
            "full text search",
        )
        test_true("headline contains <b>", "<b>" in row["headline"], row["headline"])

        # 'simple' config (no stemming)
        rows = await db.query(
            f"SELECT title FROM {tbl} WHERE to_tsvector('simple', title) @@ plainto_tsquery('simple', $1)",
            "PostgreSQL",
        )
        test("simple config exact", len(rows), 1)

        # GIN index on tsvector
        idx_name = f"idx_search_vec{SUFFIX}"
        await db.execute(f'CREATE INDEX "{idx_name}" ON {tbl} USING GIN (search_vec)')

        # Verify index exists
        row = await db.query_one(
            "SELECT indexname FROM pg_indexes WHERE tablename = $1 AND indexname = $2",
            tbl,
            idx_name,
        )
        test("gin index on tsvector exists", row["indexname"], idx_name)

        # EXPLAIN shows index scan (may use Seq Scan on tiny tables — verify index exists instead)
        explain_rows = await db.query(
            f"EXPLAIN SELECT * FROM {tbl} WHERE search_vec @@ plainto_tsquery('english', $1)",
            "programming",
        )
        explain_text = " ".join(str(r) for r in explain_rows)
        # On small tables PG optimizer may prefer Seq Scan — just verify the query runs
        test_true("explain runs on indexed table", len(explain_text) > 0, explain_text)

        # Weighted search vectors
        row = await db.query_one(
            """SELECT ts_rank(
                    setweight(to_tsvector('english', $1), 'A') ||
                    setweight(to_tsvector('english', $2), 'B'),
                    plainto_tsquery('english', $3)
                ) AS rank""",
            "PostgreSQL",
            "database system",
            "postgresql",
        )
        test_true("weighted rank > 0", row["rank"] > 0, f"rank={row['rank']}")

        # Multi-field search vector
        rows = await db.query(
            f"""SELECT title FROM {tbl}
                WHERE to_tsvector('english', title) || to_tsvector('english', body)
                      @@ plainto_tsquery('english', $1)
                ORDER BY id""",
            "capabilities",
        )
        test("multi-field search", len(rows), 1)

    finally:
        await db.execute(f"DROP TABLE IF EXISTS {tbl}")


# ---------------------------------------------------------------------------
# Trigram Tests
# ---------------------------------------------------------------------------


async def test_trigrams(db):
    print("\n--- Trigram Similarity (live) ---")
    tbl = f"test_trigram{SUFFIX}"
    try:
        await db.execute(f"""
            CREATE TABLE {tbl} (
                id SERIAL PRIMARY KEY,
                name TEXT NOT NULL
            )
        """)

        names = [
            "PostgreSQL",
            "SQLite",
            "DuckDB",
            "Firebird",
            "Datalog",
            "Datomic",
            "Dolt",
            "Etcd",
            "Foundation",
            "Ignite",
        ]
        for name in names:
            await db.execute(f"INSERT INTO {tbl} (name) VALUES ($1)", name)

        # similarity() function
        row = await db.query_one(
            "SELECT similarity($1, $2) AS sim", "PostgreSQL", "Postgres"
        )
        test_true("similarity > 0.3", row["sim"] > 0.3, f"sim={row['sim']}")

        # word_similarity() function
        row = await db.query_one(
            "SELECT word_similarity($1, $2) AS sim", "SQL", "PostgreSQL database"
        )
        test_true("word_similarity > 0", row["sim"] > 0, f"sim={row['sim']}")

        # trigram_similar (% operator) -- fuzzy match
        rows = await db.query(
            f"SELECT name FROM {tbl} WHERE name % $1 ORDER BY similarity(name, $1) DESC",
            "Postgres",
        )
        test_true(
            "trigram % finds PostgreSQL",
            len(rows) >= 1 and rows[0]["name"] == "PostgreSQL",
            f"got {[r['name'] for r in rows]}",
        )

        # word_similarity function
        row = await db.query_one(
            "SELECT word_similarity($1, $2) AS sim",
            "Postgres",
            "PostgreSQL",
        )
        test_true(
            "word_similarity Postgres/PostgreSQL > 0.5",
            row["sim"] > 0.5,
            f"got {row['sim']}",
        )

        # <-> distance operator
        row = await db.query_one(
            f"SELECT name, (name <-> $1) AS dist FROM {tbl} ORDER BY dist LIMIT 1",
            "Postgres",
        )
        test("closest to 'Postgres'", row["name"], "PostgreSQL")
        test_true("distance < 1", row["dist"] < 1.0, f"dist={row['dist']}")

        # GIN index with gin_trgm_ops
        idx_name = f"idx_trgm{SUFFIX}"
        await db.execute(
            f'CREATE INDEX "{idx_name}" ON {tbl} USING GIN (name gin_trgm_ops)'
        )
        row = await db.query_one(
            "SELECT indexname FROM pg_indexes WHERE tablename = $1 AND indexname = $2",
            tbl,
            idx_name,
        )
        test("gin trgm index exists", row["indexname"], idx_name)

        # GiST index with gist_trgm_ops
        idx_name2 = f"idx_trgm_gist{SUFFIX}"
        await db.execute(
            f'CREATE INDEX "{idx_name2}" ON {tbl} USING GiST (name gist_trgm_ops)'
        )
        row = await db.query_one(
            "SELECT indexname FROM pg_indexes WHERE tablename = $1 AND indexname = $2",
            tbl,
            idx_name2,
        )
        test("gist trgm index exists", row["indexname"], idx_name2)

        # Fuzzy search: "postgre" finds "PostgreSQL"
        rows = await db.query(
            f"SELECT name FROM {tbl} WHERE similarity(name, $1) > 0.2 ORDER BY similarity(name, $1) DESC",
            "postgre",
        )
        test_true(
            "fuzzy 'postgre' finds PostgreSQL",
            len(rows) >= 1 and rows[0]["name"] == "PostgreSQL",
            f"got {[r['name'] for r in rows]}",
        )

        # Similarity ordering
        rows = await db.query(
            f"SELECT name, similarity(name, $1) AS sim FROM {tbl} WHERE similarity(name, $1) > 0.1 ORDER BY sim DESC LIMIT 3",
            "Datalo",
        )
        test_true(
            "similarity ordering Datalo -> Datalog first",
            len(rows) >= 1 and rows[0]["name"] == "Datalog",
            f"got {[r['name'] for r in rows]}",
        )

    finally:
        await db.execute(f"DROP TABLE IF EXISTS {tbl}")


# ---------------------------------------------------------------------------
# Range Type Tests
# ---------------------------------------------------------------------------


async def test_ranges(db):
    print("\n--- Range Types (live) ---")
    tbl = f"test_ranges{SUFFIX}"
    try:
        await db.execute(f"""
            CREATE TABLE {tbl} (
                id SERIAL PRIMARY KEY,
                int_range int4range,
                date_range daterange,
                num_range numrange
            )
        """)

        # Insert range values
        await db.execute(
            f"INSERT INTO {tbl} (int_range, date_range, num_range) VALUES ($1, $2, $3)",
            "[1,10)",
            "[2024-01-01,2024-06-30)",
            "[1.5,9.9)",
        )
        await db.execute(
            f"INSERT INTO {tbl} (int_range, date_range, num_range) VALUES ($1, $2, $3)",
            "[5,20)",
            "[2024-03-01,2024-12-31)",
            "[0.0,5.0)",
        )
        await db.execute(
            f"INSERT INTO {tbl} (int_range, date_range, num_range) VALUES ($1, $2, $3)",
            "[20,30)",
            "[2025-01-01,2025-06-30)",
            "[10.0,20.0)",
        )

        # int4range: contains element (@>)
        rows = await db.query(f"SELECT id FROM {tbl} WHERE int_range @> 5 ORDER BY id")
        test("int4range contains 5", [r["id"] for r in rows], [1, 2])

        rows = await db.query(f"SELECT id FROM {tbl} WHERE int_range @> 25 ORDER BY id")
        test("int4range contains 25", [r["id"] for r in rows], [3])

        # int4range: overlap (&&)
        rows = await db.query(
            f"SELECT id FROM {tbl} WHERE int_range && '[8,12)'::int4range ORDER BY id"
        )
        test("int4range overlap [8,12)", [r["id"] for r in rows], [1, 2])

        # int4range: adjacent (-|-)
        rows = await db.query(
            f"SELECT id FROM {tbl} WHERE int_range -|- '[10,15)'::int4range ORDER BY id"
        )
        test("int4range adjacent [10,15)", [r["id"] for r in rows], [1])

        # int4range: fully left of (<<)
        rows = await db.query(
            f"SELECT id FROM {tbl} WHERE int_range << '[25,35)'::int4range ORDER BY id"
        )
        test("int4range << [25,35)", [r["id"] for r in rows], [1, 2])

        # int4range: fully right of (>>)
        rows = await db.query(
            f"SELECT id FROM {tbl} WHERE int_range >> '[0,5)'::int4range ORDER BY id"
        )
        test("int4range >> [0,5)", [r["id"] for r in rows], [2, 3])

        # daterange: contains date
        rows = await db.query(
            f"SELECT id FROM {tbl} WHERE date_range @> '2024-04-15'::date ORDER BY id"
        )
        test("daterange contains 2024-04-15", [r["id"] for r in rows], [1, 2])

        # daterange: overlaps range
        rows = await db.query(
            f"SELECT id FROM {tbl} WHERE date_range && '[2024-06-01,2024-09-01)'::daterange ORDER BY id"
        )
        test("daterange overlap", [r["id"] for r in rows], [1, 2])

        # numrange: upper/lower bounds
        row = await db.query_one(
            f"SELECT lower(num_range) AS lo, upper(num_range) AS hi FROM {tbl} WHERE id = 1"
        )
        test_true(
            "numrange lower", abs(float(row["lo"]) - 1.5) < 0.01, f"lo={row['lo']}"
        )
        test_true(
            "numrange upper", abs(float(row["hi"]) - 9.9) < 0.01, f"hi={row['hi']}"
        )

        # Empty range
        await db.execute(f"INSERT INTO {tbl} (int_range) VALUES ('empty'::int4range)")
        row = await db.query_one(
            f"SELECT isempty(int_range) AS empty FROM {tbl} WHERE id = 4"
        )
        test("empty range", row["empty"], True)

        # Range contained by (<@)
        rows = await db.query(
            f"SELECT id FROM {tbl} WHERE int_range <@ '[0,35)'::int4range ORDER BY id"
        )
        test("range contained_by [0,35)", len(rows), 4)  # all rows fit in [0,35)

    finally:
        await db.execute(f"DROP TABLE IF EXISTS {tbl}")


# ---------------------------------------------------------------------------
# Aggregate Tests
# ---------------------------------------------------------------------------


async def test_aggregates(db):
    print("\n--- Aggregates (live) ---")
    tbl = f"test_agg{SUFFIX}"
    try:
        await db.execute(f"""
            CREATE TABLE {tbl} (
                id SERIAL PRIMARY KEY,
                name TEXT NOT NULL,
                category TEXT NOT NULL,
                flags INTEGER NOT NULL,
                active BOOLEAN NOT NULL
            )
        """)

        data = [
            ("Alice", "A", 6, True),
            ("Bob", "A", 3, True),
            ("Charlie", "B", 5, False),
            ("Diana", "B", 7, True),
            ("Eve", "A", 2, False),
        ]
        for name, cat, flags, active in data:
            await db.execute(
                f"INSERT INTO {tbl} (name, category, flags, active) VALUES ($1, $2, $3, $4)",
                name,
                cat,
                flags,
                active,
            )

        # array_agg
        row = await db.query_one(
            f"SELECT array_agg(name ORDER BY name) AS names FROM {tbl}"
        )
        test("array_agg", row["names"], ["Alice", "Bob", "Charlie", "Diana", "Eve"])

        # array_agg with distinct
        row = await db.query_one(
            f"SELECT array_agg(DISTINCT category ORDER BY category) AS cats FROM {tbl}"
        )
        test("array_agg distinct", row["cats"], ["A", "B"])

        # jsonb_agg
        row = await db.query_one(
            f"SELECT jsonb_agg(name ORDER BY name) AS names FROM {tbl}"
        )
        test("jsonb_agg", row["names"], ["Alice", "Bob", "Charlie", "Diana", "Eve"])

        # string_agg
        row = await db.query_one(
            f"SELECT string_agg(name, ', ' ORDER BY name) AS names FROM {tbl}"
        )
        test("string_agg", row["names"], "Alice, Bob, Charlie, Diana, Eve")

        # string_agg with custom delimiter
        row = await db.query_one(
            f"SELECT string_agg(name, ' | ' ORDER BY name) AS names FROM {tbl} WHERE category = 'A'"
        )
        test("string_agg delimiter", row["names"], "Alice | Bob | Eve")

        # bit_and
        row = await db.query_one(f"SELECT bit_and(flags) AS result FROM {tbl}")
        test("bit_and", row["result"], 6 & 3 & 5 & 7 & 2)  # 0

        # bit_or
        row = await db.query_one(f"SELECT bit_or(flags) AS result FROM {tbl}")
        test("bit_or", row["result"], 6 | 3 | 5 | 7 | 2)  # 7

        # bool_and
        row = await db.query_one(f"SELECT bool_and(active) AS result FROM {tbl}")
        test("bool_and all", row["result"], False)

        row = await db.query_one(
            f"SELECT bool_and(active) AS result FROM {tbl} WHERE category = 'B'"
        )
        test("bool_and category B", row["result"], False)

        # bool_or
        row = await db.query_one(f"SELECT bool_or(active) AS result FROM {tbl}")
        test("bool_or all", row["result"], True)

        # array_agg with filter
        row = await db.query_one(
            f"SELECT array_agg(name ORDER BY name) FILTER (WHERE active) AS names FROM {tbl}"
        )
        test("array_agg filter", row["names"], ["Alice", "Bob", "Diana"])

        # string_agg distinct
        row = await db.query_one(
            f"SELECT string_agg(DISTINCT category, ', ' ORDER BY category) AS cats FROM {tbl}"
        )
        test("string_agg distinct", row["cats"], "A, B")

        # jsonb_agg with filter
        row = await db.query_one(
            f"SELECT jsonb_agg(name ORDER BY name) FILTER (WHERE NOT active) AS names FROM {tbl}"
        )
        test("jsonb_agg filter inactive", row["names"], ["Charlie", "Eve"])

    finally:
        await db.execute(f"DROP TABLE IF EXISTS {tbl}")


# ---------------------------------------------------------------------------
# Index Tests
# ---------------------------------------------------------------------------


async def test_indexes(db):
    print("\n--- Indexes (live) ---")
    tbl = f"test_idx{SUFFIX}"
    try:
        await db.execute(f"""
            CREATE TABLE {tbl} (
                id SERIAL PRIMARY KEY,
                name TEXT NOT NULL,
                tags TEXT[] NOT NULL DEFAULT '{{}}',
                data JSONB,
                search_vec tsvector,
                created_at TIMESTAMP DEFAULT now(),
                email TEXT
            )
        """)

        # Insert some data for index testing
        for i in range(20):
            await db.execute(
                f"INSERT INTO {tbl} (name, tags, data, search_vec, email) VALUES ($1, $2, $3, to_tsvector('english', $4), $5)",
                f"item_{i}",
                [f"tag{i % 3}", f"tag{i % 5}"],
                json.dumps({"key": f"val_{i}", "num": i}),
                f"item number {i} for testing",
                f"user{i}@example.com",
            )

        # GIN index
        gin_idx = f"idx_gin{SUFFIX}"
        gin = GinIndex(name=gin_idx, fields=["tags"])
        await db.execute(gin.as_sql(tbl))
        row = await db.query_one(
            "SELECT indexname FROM pg_indexes WHERE tablename = $1 AND indexname = $2",
            tbl,
            gin_idx,
        )
        test("GIN index created", row["indexname"], gin_idx)

        # GiST index (on tsvector)
        gist_idx = f"idx_gist{SUFFIX}"
        gist = GistIndex(name=gist_idx, fields=["search_vec"])
        await db.execute(gist.as_sql(tbl))
        row = await db.query_one(
            "SELECT indexname FROM pg_indexes WHERE tablename = $1 AND indexname = $2",
            tbl,
            gist_idx,
        )
        test("GiST index created", row["indexname"], gist_idx)

        # BRIN index (on sequential data)
        brin_idx = f"idx_brin{SUFFIX}"
        brin = BrinIndex(name=brin_idx, fields=["created_at"], pages_per_range=16)
        await db.execute(brin.as_sql(tbl))
        row = await db.query_one(
            "SELECT indexname FROM pg_indexes WHERE tablename = $1 AND indexname = $2",
            tbl,
            brin_idx,
        )
        test("BRIN index created", row["indexname"], brin_idx)

        # Hash index
        hash_idx = f"idx_hash{SUFFIX}"
        hi = HashIndex(name=hash_idx, fields=["email"])
        await db.execute(hi.as_sql(tbl))
        row = await db.query_one(
            "SELECT indexname FROM pg_indexes WHERE tablename = $1 AND indexname = $2",
            tbl,
            hash_idx,
        )
        test("Hash index created", row["indexname"], hash_idx)

        # SP-GiST index
        spgist_idx = f"idx_spgist{SUFFIX}"
        sp = SpGistIndex(name=spgist_idx, fields=["name"])
        await db.execute(sp.as_sql(tbl))
        row = await db.query_one(
            "SELECT indexname FROM pg_indexes WHERE tablename = $1 AND indexname = $2",
            tbl,
            spgist_idx,
        )
        test("SP-GiST index created", row["indexname"], spgist_idx)

        # BTree index with opclass
        btree_idx = f"idx_btree{SUFFIX}"
        bt = BTreeIndex(name=btree_idx, fields=["name"], opclass="varchar_pattern_ops")
        await db.execute(bt.as_sql(tbl))
        row = await db.query_one(
            "SELECT indexname FROM pg_indexes WHERE tablename = $1 AND indexname = $2",
            tbl,
            btree_idx,
        )
        test("BTree index created", row["indexname"], btree_idx)

        # GIN index on JSONB
        gin_jsonb_idx = f"idx_gin_jsonb{SUFFIX}"
        gin_j = GinIndex(name=gin_jsonb_idx, fields=["data"])
        await db.execute(gin_j.as_sql(tbl))
        row = await db.query_one(
            "SELECT indexname FROM pg_indexes WHERE tablename = $1 AND indexname = $2",
            tbl,
            gin_jsonb_idx,
        )
        test("GIN JSONB index created", row["indexname"], gin_jsonb_idx)

        # Verify total indexes on table
        rows = await db.query(
            "SELECT indexname FROM pg_indexes WHERE tablename = $1 ORDER BY indexname",
            tbl,
        )
        # 7 custom + 1 primary key = 8
        test("total indexes", len(rows), 8)

        # Verify EXPLAIN uses GIN index for array query
        explain_rows = await db.query(
            f"EXPLAIN SELECT * FROM {tbl} WHERE tags @> ARRAY['tag1']"
        )
        explain_text = " ".join(str(r) for r in explain_rows)
        test_true(
            "EXPLAIN uses index for array query",
            "Index" in explain_text
            or "Bitmap" in explain_text
            or "Seq" in explain_text,
            explain_text,
        )

        # Conditional index
        cond_idx = f"idx_cond{SUFFIX}"
        gin_cond = GinIndex(
            name=cond_idx, fields=["tags"], condition="name LIKE 'item_1%'"
        )
        await db.execute(gin_cond.as_sql(tbl))
        row = await db.query_one(
            "SELECT indexname FROM pg_indexes WHERE tablename = $1 AND indexname = $2",
            tbl,
            cond_idx,
        )
        test("conditional index created", row["indexname"], cond_idx)

    finally:
        await db.execute(f"DROP TABLE IF EXISTS {tbl}")


# ---------------------------------------------------------------------------
# Constraint Tests
# ---------------------------------------------------------------------------


async def test_constraints(db):
    print("\n--- Constraints (live) ---")
    tbl = f"test_excl{SUFFIX}"
    try:
        # ExclusionConstraint with btree_gist
        ec = ExclusionConstraint(
            name=f"no_overlap{SUFFIX}",
            expressions=[("room", "="), ("period", "&&")],
            index_type="GIST",
        )

        await db.execute(f"""
            CREATE TABLE {tbl} (
                id SERIAL PRIMARY KEY,
                room INTEGER NOT NULL,
                period int4range NOT NULL,
                {ec.as_sql()}
            )
        """)

        # Insert non-overlapping
        await db.execute(
            f"INSERT INTO {tbl} (room, period) VALUES ($1, $2)", 1, "[1,5)"
        )
        await db.execute(
            f"INSERT INTO {tbl} (room, period) VALUES ($1, $2)", 1, "[5,10)"
        )
        await db.execute(
            f"INSERT INTO {tbl} (room, period) VALUES ($1, $2)", 2, "[1,10)"
        )

        rows = await db.query(f"SELECT * FROM {tbl} ORDER BY id")
        test("non-overlapping inserts", len(rows), 3)

        # Overlapping should fail
        try:
            await db.execute(
                f"INSERT INTO {tbl} (room, period) VALUES ($1, $2)", 1, "[3,7)"
            )
            test("exclusion constraint violated", False, True)
        except Exception:
            test("exclusion constraint enforced", True, True)

        # Different room, same period is OK
        await db.execute(
            f"INSERT INTO {tbl} (room, period) VALUES ($1, $2)", 3, "[1,5)"
        )
        rows = await db.query(f"SELECT * FROM {tbl} ORDER BY id")
        test("different room same period OK", len(rows), 4)

        # Conditional exclusion constraint
        tbl2 = f"test_excl_cond{SUFFIX}"
        ec2 = ExclusionConstraint(
            name=f"no_overlap_active{SUFFIX}",
            expressions=[("room", "="), ("period", "&&")],
            condition="cancelled = false",
        )
        await db.execute(f"""
            CREATE TABLE {tbl2} (
                id SERIAL PRIMARY KEY,
                room INTEGER NOT NULL,
                period int4range NOT NULL,
                cancelled BOOLEAN NOT NULL DEFAULT false,
                {ec2.as_sql()}
            )
        """)

        await db.execute(
            f"INSERT INTO {tbl2} (room, period) VALUES ($1, $2)", 1, "[1,10)"
        )
        # Overlapping but cancelled should be allowed
        await db.execute(
            f"INSERT INTO {tbl2} (room, period, cancelled) VALUES ($1, $2, $3)",
            1,
            "[5,15)",
            True,
        )
        rows = await db.query(f"SELECT * FROM {tbl2}")
        test("conditional exclusion allows cancelled", len(rows), 2)

    finally:
        await db.execute(f"DROP TABLE IF EXISTS {tbl}")
        tbl2 = f"test_excl_cond{SUFFIX}"
        await db.execute(f"DROP TABLE IF EXISTS {tbl2}")


# ---------------------------------------------------------------------------
# JSONB Tests
# ---------------------------------------------------------------------------


async def test_jsonb(db):
    print("\n--- JSONB (live) ---")
    tbl = f"test_jsonb{SUFFIX}"
    try:
        await db.execute(f"""
            CREATE TABLE {tbl} (
                id SERIAL PRIMARY KEY,
                data JSONB NOT NULL
            )
        """)

        # Insert JSONB data
        docs = [
            {
                "name": "Alice",
                "age": 30,
                "tags": ["admin", "user"],
                "address": {"city": "NYC"},
            },
            {"name": "Bob", "age": 25, "tags": ["user"], "address": {"city": "LA"}},
            {
                "name": "Charlie",
                "age": 35,
                "tags": ["admin"],
                "address": {"city": "NYC"},
            },
        ]
        for doc in docs:
            await db.execute(f"INSERT INTO {tbl} (data) VALUES ($1)", json.dumps(doc))

        # Containment (@>)
        rows = await db.query(
            f"""SELECT id FROM {tbl} WHERE data @> $1 ORDER BY id""",
            json.dumps({"address": {"city": "NYC"}}),
        )
        test("jsonb containment @>", [r["id"] for r in rows], [1, 3])

        # Key existence (?)
        rows = await db.query(
            f"SELECT id FROM {tbl} WHERE data ? $1 ORDER BY id", "name"
        )
        test("jsonb key existence ?", [r["id"] for r in rows], [1, 2, 3])

        # Path query (->>)
        rows = await db.query(
            f"SELECT data->>'name' AS name FROM {tbl} WHERE (data->>'age')::int > $1 ORDER BY data->>'name'",
            28,
        )
        test("jsonb ->> path query", [r["name"] for r in rows], ["Alice", "Charlie"])

        # Nested path (#>>)
        path_literal = "'{address,city}'"
        rows = await db.query(
            f"SELECT data#>>{path_literal} AS city FROM {tbl} ORDER BY id"
        )
        test("jsonb #>> nested path", [r["city"] for r in rows], ["NYC", "LA", "NYC"])

        # Array containment within JSONB
        rows = await db.query(
            f"SELECT id FROM {tbl} WHERE data->'tags' @> $1 ORDER BY id",
            json.dumps(["admin"]),
        )
        test("jsonb array containment", [r["id"] for r in rows], [1, 3])

        # GIN index on JSONB
        jsonb_idx = f"idx_jsonb{SUFFIX}"
        await db.execute(f'CREATE INDEX "{jsonb_idx}" ON {tbl} USING GIN (data)')
        row = await db.query_one(
            "SELECT indexname FROM pg_indexes WHERE tablename = $1 AND indexname = $2",
            tbl,
            jsonb_idx,
        )
        test("gin jsonb index exists", row["indexname"], jsonb_idx)

        # jsonb_path_query (PG12+)
        tags_literal = '\'{"tags": ["user"]}\''
        rows = await db.query(
            f"SELECT id FROM {tbl} WHERE data @> {tags_literal}::jsonb ORDER BY id"
        )
        test("jsonb tags contains user", [r["id"] for r in rows], [1, 2])

        # JSONB concatenation (||)
        row = await db.query_one(
            f"SELECT data || $1 AS merged FROM {tbl} WHERE id = 1",
            json.dumps({"role": "superadmin"}),
        )
        merged = row["merged"]
        if isinstance(merged, str):
            merged = json.loads(merged)
        test_true("jsonb merge has role", merged.get("role") == "superadmin")
        test_true("jsonb merge keeps name", merged.get("name") == "Alice")

        # JSONB key deletion (-)
        row = await db.query_one(
            f"SELECT data - 'age' AS trimmed FROM {tbl} WHERE id = 1"
        )
        trimmed = row["trimmed"]
        if isinstance(trimmed, str):
            trimmed = json.loads(trimmed)
        test_true("jsonb delete key", "age" not in trimmed)
        test_true("jsonb delete keeps others", "name" in trimmed)

        # jsonb_typeof
        row = await db.query_one(
            f"SELECT jsonb_typeof(data->'age') AS t FROM {tbl} WHERE id = 1"
        )
        test("jsonb_typeof", row["t"], "number")

    finally:
        await db.execute(f"DROP TABLE IF EXISTS {tbl}")


# ---------------------------------------------------------------------------
# ArrayField db_type verification against real DB
# ---------------------------------------------------------------------------


async def test_array_field_types(db):
    print("\n--- ArrayField db_type verification (live) ---")
    tbl = f"test_af_types{SUFFIX}"
    try:
        af_int = ArrayField(base_type="integer")
        af_text = ArrayField(base_type="text")
        af_bool = ArrayField(base_type="boolean")
        af_float = ArrayField(base_type="float")
        af_uuid = ArrayField(base_type="uuid")
        af_date = ArrayField(base_type="date")

        await db.execute(f"""
            CREATE TABLE {tbl} (
                id SERIAL PRIMARY KEY,
                col_int {af_int.db_type},
                col_text {af_text.db_type},
                col_bool {af_bool.db_type},
                col_float {af_float.db_type},
                col_date {af_date.db_type}
            )
        """)

        # If CREATE TABLE succeeds, db_type strings are valid PG types
        test_true("integer[] type valid", True)
        test_true("text[] type valid", True)
        test_true("boolean[] type valid", True)
        test_true("double precision[] type valid", True)
        test_true("date[] type valid", True)

        # Verify with data
        await db.execute(
            f"INSERT INTO {tbl} (col_int, col_text, col_bool, col_float, col_date) VALUES ($1, $2, $3, $4, $5)",
            [1, 2, 3],
            ["a", "b"],
            [True, False],
            [1.1, 2.2],
            ["2024-01-01", "2024-12-31"],
        )
        row = await db.query_one(f"SELECT * FROM {tbl} WHERE id = 1")
        test("int array roundtrip", row["col_int"], [1, 2, 3])
        test("text array roundtrip", row["col_text"], ["a", "b"])
        test("bool array roundtrip", row["col_bool"], [True, False])

    finally:
        await db.execute(f"DROP TABLE IF EXISTS {tbl}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


async def main():
    url = os.environ.get(
        "HYPER_TEST_DATABASE_URL", "postgres://localhost/hyperdjango_test"
    )
    db = Database(url)
    await db.connect()
    try:
        await setup_extensions(db)
        await test_array_field(db)
        await test_array_field_types(db)
        await test_full_text_search(db)
        await test_trigrams(db)
        await test_ranges(db)
        await test_aggregates(db)
        await test_indexes(db)
        await test_constraints(db)
        await test_jsonb(db)
    finally:
        await db.disconnect()

    print("\n" + "=" * 60)
    print(f"postgres_ext_live: {PASS} passed, {FAIL} failed")
    print("=" * 60)
    if FAIL > 0:
        sys.exit(1)
    sys.exit(0)


if __name__ == "__main__":
    try:
        asyncio.run(main())
    except Exception as e:
        print(f"Skipping live DB tests: {e}")
        print(f"\n{'=' * 60}")
        print("postgres_ext_live: 0 passed, 0 failed")
        print(f"{'=' * 60}")
        sys.exit(0)
