/*
 * Copyright 2016-2018 Uber Technologies, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/** @file baseCells.h
 * @brief   Base cell related lookup tables and access functions.
 */

#ifndef BASECELLS_H
#define BASECELLS_H

#include <stdint.h>

#include "constants.h"
#include "coordijk.h"
#include "faceijk.h"

/** @struct BaseCellData
 * @brief information on a single base cell
 */
typedef struct {
    FaceIJK
        homeFijk;   ///< "home" face and normalized ijk coordinates on that face
    int isPentagon; ///< is this base cell a pentagon?
    int cwOffsetPent[2]; ///< if a pentagon, what are its two clockwise offset
                         /// faces?
} BaseCellData;

/** @struct BaseCellRotation
 *  @brief base cell at a given ijk and required rotations into its system.
 *  Exposed via the header so the small `_faceIjkToBaseCell{,CCWrot60}` lookup
 *  helpers below can be `static inline` and fold into hot encoder paths.
 */
typedef struct {
    int baseCell; ///< base cell number
    int ccwRot60; ///< number of ccw 60 degree rotations relative to current
                  /// face
} BaseCellRotation;

#define INVALID_BASE_CELL 127
extern const int baseCellNeighbors[NUM_BASE_CELLS][7];
extern const int baseCellNeighbor60CCWRots[NUM_BASE_CELLS][7];

// resolution 0 base cell data lookup-table (global)
extern const BaseCellData baseCellData[NUM_BASE_CELLS];

/* Face × IJK → base cell + ccw rotation lookup. Exposed so the inline
 * helpers below can read it directly. */
extern const BaseCellRotation faceIjkBaseCells[NUM_ICOSA_FACES][3][3][3];

/* 128-bit bitmap: bit i set iff base cell i is a pentagon. Replaces the
 * per-call struct-field load from baseCellData[bc].isPentagon. The struct
 * array spans ~3.9 KB across many cache lines; the bitmap is 16 bytes —
 * one quarter of a cache line — so callers in hot loops keep their L1d
 * working set tight. Generated by
 * scripts/dev/gen-base-cell-pentagon-bitmap.py. */
extern const uint64_t baseCellPentagonBitmap[2];

/** Maximum input for any component to face-to-base-cell lookup functions */
#define MAX_FACE_COORD 2

/** Invalid number of rotations */
#define INVALID_ROTATIONS -1

// Internal functions

/* `_isBaseCellPentagon` is hot enough (called from 14+ sites in the
 * H3 core, top-of-profile across 7 benches) that it lives in the header
 * as `static inline`. The (unsigned) cast collapses the bc<0 and
 * bc>=NUM_BASE_CELLS bounds checks into one comparison. */
static inline int _isBaseCellPentagon(int baseCell) {
    if ((unsigned)baseCell >= (unsigned)NUM_BASE_CELLS) {
        return 0;
    }
    return (int)((baseCellPentagonBitmap[(unsigned)baseCell >> 6] >>
                  ((unsigned)baseCell & 63)) &
                 UINT64_C(1));
}

/* `_isBaseCellPolarPentagon` and `_baseCellIsCwOffset` are tiny
 * predicates that the gridDisk pentagon path calls from inside
 * `h3NeighborRotations`. The bodies are 1–2 comparisons each — inline
 * they fold into the surrounding branch. Same `static inline` pattern
 * as `_isBaseCellPentagon` above. */
static inline bool _isBaseCellPolarPentagon(int baseCell) {
    return baseCell == 4 || baseCell == 117;
}

static inline bool _baseCellIsCwOffset(int baseCell, int testFace) {
    return baseCellData[baseCell].cwOffsetPent[0] == testFace ||
           baseCellData[baseCell].cwOffsetPent[1] == testFace;
}

/* Three small lookups used in the encoder/decoder hot paths. The bodies
 * are single table-loads each so cross-TU inlining via static inline pays
 * off — folds them into the surrounding digit walk in `_faceIjkToH3` and
 * `vec3ToCell`, eliminating a function-call boundary per encoded cell. */
static inline int _faceIjkToBaseCell(const FaceIJK *h) {
    return faceIjkBaseCells[h->face][h->coord.i][h->coord.j][h->coord.k]
        .baseCell;
}
static inline int _faceIjkToBaseCellCCWrot60(const FaceIJK *h) {
    return faceIjkBaseCells[h->face][h->coord.i][h->coord.j][h->coord.k]
        .ccwRot60;
}
static inline void _baseCellToFaceIjk(int baseCell, FaceIJK *h) {
    *h = baseCellData[baseCell].homeFijk;
}
int _baseCellToCCWrot60(int baseCell, int face);

/* `_getBaseCellNeighbor` is a single 1-D table load — inline so the
 * surrounding `h3NeighborRotations` / `gridDisk` walk skips a function
 * call boundary per direction step. */
static inline int _getBaseCellNeighbor(int baseCell, Direction dir) {
    return baseCellNeighbors[baseCell][dir];
}
int _getBaseCellNeighbor(int baseCell, Direction dir);
Direction _getBaseCellDirection(int originBaseCell, int destinationBaseCell);

#endif
